export type Locale = "en" | "zh" | "ja" | "ko"
export type Theme = "dark" | "light"
export type Dictionary = Record<string, any>

export const dictionaries: Record<Locale, Dictionary> = {
    en: {
        nav: {
            literature: "LITERATURE",
            vocabulary: "VOCABULARY",
            progress: "PROGRESS",
            cards: "CARDS",
            pricing: "PRICING",
            title: "How To Say",
            tagline: "Language boundaries shape the world.",
        },
        menu: {
            openToolsMenu: "Open tools menu",
            quickSearch: "Quick Search",
            cardsPreview: "Cards",
            previewTag: "Preview",
            savedLiterature: "Literature",
            dailyGuess: "Daily Guess",
            imageMode: "Image Mode",
            gradingExercise: "Grading Exercise",
            chromeExtension: "Chrome Extension",
            about: "About",
            appearance: "Appearance",
            language: "Language",
            darkMode: "Dark",
            lightMode: "Light",
            english: "English",
            chinese: "中文",
            japanese: "日本語",
            korean: "한국어",
        },
        auth: {
            loading: "Loading...",
            signIn: "Sign In",
            level: "Level",
            assessYourLevel: "Assess your level",
            signOut: "Sign Out",
            expireAt: "Expire at",
        },
        search: {
            open: "Open quick search",
            title: "Quick Word Search",
            description: "Search a word without leaving the page.",
            shortcutHint: "Shortcut: Ctrl/Cmd + K",
            placeholder: "Type a word",
            submit: "Search",
            searching: "Searching...",
            empty: "Search for a word to see its definition.",
            notFound: "We couldn't find that word.",
            examples: "Examples",
            phonetic: "Phonetic",
            definition: "Definition",
            close: "Close",
            chinese: "Chinese",
        },
        common: {
            backHome: "Back Home",
            backToLiterature: "Back to Literature",
            archived: "Archived",
            noDescription: "No description yet.",
            cancel: "Cancel",
        },
        savedLiterature: {
            title: "Saved Literature",
            intro: "A reading shelf for the passages you starred from the homepage.",
            loginTitle: "Sign in to view saved literature",
            loginBody: "Saved passages are tied to your account, so we need you signed in before we can load your reading shelf.",
            loginCta: "Sign in to continue",
            loading: "Loading saved passages...",
            emptyTitle: "No saved passages yet",
            emptyBody: "When you favorite a literature passage on the homepage, it will appear here.",
            savedCount: "{count} saved passages",
            openLiterature: "Browse literature",
        },
        cards: {
            title: "Cards",
            marketingTitle: "Build decks from the words you actually meet.",
            marketingBody: "Turn reading and lookup into a reusable review system. Create decks, collect hard words, and keep spaced review tied to your own material.",
            feature1Title: "Create focused decks",
            feature1Body: "Separate exam vocabulary, literature, or topic-based cards instead of mixing everything together.",
            feature2Title: "Review what is due",
            feature2Body: "See what needs attention now and keep your review sessions short and consistent.",
            feature3Title: "Stay close to context",
            feature3Body: "Cards work best when they come from sentences and passages you have already seen.",
            loginCta: "Sign in to open cards",
            decksTitle: "Your deck workspace",
            decksBody: "Create small focused decks, keep an eye on due volume, and jump into review when you are ready.",
            statsDecks: "Decks",
            statsCards: "Cards",
            statsDueNow: "Due now",
            openReview: "Open review",
            createDeckTitle: "Create a new deck",
            createDeckBody: "Use short, specific names so each deck stays useful over time.",
            deckName: "Deck name",
            deckDescription: "Description",
            createDeck: "Create deck",
            creatingDeck: "Creating...",
            createDeckFailed: "Failed to create deck.",
            libraryTitle: "Deck library",
            libraryBody: "Open a deck to add cards, inspect due counts, and review its contents.",
            loadingDecks: "Loading decks...",
            emptyDecks: "No decks yet. Create your first one above.",
            loadDecksFailed: "Failed to load decks.",
            cardsCount: "{count} cards",
            dueCount: "{count} due",
            newCount: "{count} new",
        },
        cardsReview: {
            title: "Cards Review",
            marketingTitle: "Review any saved topic on a memory schedule",
            marketingBody: "The cards review center gathers due cards across your decks, lets you flip each one, then grade recall with Anki-style ratings.",
            statDueNow: "Due now",
            statOverdue: "Overdue",
            statDueToday: "Due today",
            statNewCards: "New cards",
            statDueNowBody: "See what needs attention immediately.",
            statOverdueBody: "Spot cards that have slipped past their ideal interval.",
            statDeckFilterBody: "Focus on one deck or clear a mixed queue.",
            deckFilter: "Deck filter",
            loginCta: "Login to review cards",
            backToCards: "Back to cards",
            queueTitle: "Memory queue for your custom decks",
            queueBody: "Review what is due right now, inspect overdue load, then start a self-graded card round.",
            allDecks: "All decks",
            startReview: "Start review",
            loadingCenter: "Loading cards review center...",
            decksWithDueCards: "Decks with due cards",
            noDueCards: "No due cards right now.",
            cardsCount: "{count} cards",
            newCount: "{count} new",
            dueCount: "{count} due",
            overdueCount: "{count} overdue",
            currentRoundPreview: "Current round preview",
            filteredToOneDeck: "This queue is filtered to one deck.",
            blendedQueue: "This queue blends all currently due decks.",
            cardsLabel: "Cards",
            noCardsInFilter: "No cards are due in this filter.",
            nothingReady: "Nothing is ready to review yet.",
            continue: "Continue",
            noCardsLeft: "No cards left in this round.",
            backToCenter: "Back to review center",
            closeRound: "Close round",
            prompt: "Prompt",
            answer: "Answer",
            revealHelp: "Reveal the answer when you are ready to grade your recall.",
            notes: "Notes",
            revealAnswer: "Reveal answer",
            again: "Again",
            hard: "Hard",
            good: "Good",
            easy: "Easy",
            unableToLoad: "Unable to load cards review.",
            unableToSave: "Unable to save review result.",
            cardProgress: "Card {current} of {total} · {badge}",
            badges: {
                new: "new",
                learning: "learning",
                review: "in review",
                mastered: "mastered",
                fragile: "fragile",
                building: "building",
                stable: "stable",
            },
        },
        vocabulary: {
            title: "Your vocabulary library",
            description: "Browse saved words, filter by familiarity, and turn your collection into active practice whenever you want.",
            feature1Title: "Save useful words",
            feature1Body: "Keep words that came from reading, practice, and lookup in one place.",
            feature2Title: "Filter by memory state",
            feature2Body: "Separate fragile words from stable ones so review time goes where it matters.",
            feature3Title: "Practice from your own list",
            feature3Body: "Start training directly from the vocabulary you have already collected.",
            loginCta: "Sign in to open vocabulary",
            library: "Vocabulary",
            memoryFilter: "Filter: {label}",
            searchPlaceholder: "Search your words",
            importWords: "Import words",
            practise: "Practice",
            practiseSavedWords: "Practice saved words",
            openCustomPractise: "Open custom practice",
        },
        listMenu: {
            allWords: "All words",
            unfamiliar: "Unfamiliar",
            familiarity1: "Familiarity 1",
            familiarity2: "Familiarity 2",
            familiarity3: "Familiarity 3",
            familiarity4: "Familiarity 4",
            familiarity5: "Familiarity 5",
            ignored: "Ignored",
        },
        inputModal: {
            title: "Import words",
            placeholder: "Paste words here, separated by spaces, commas, or new lines.",
            confirm: "Import",
            cancel: "Cancel",
        },
        wordBook: {
            word: "Word",
            memory: "Memory",
            familiarity: "Familiarity",
            query: "Queries",
            actions: "Actions",
            definition: "Definition",
            loadingDefinition: "Loading definition...",
            fragile: "Fragile",
            building: "Building",
            stable: "Stable",
            mastered: "Mastered",
            untracked: "Untracked",
            ignoreWord: "Ignore word",
            listenOnYouGlish: "Listen on YouGlish",
            removeWord: "Remove word",
            empty: "No saved words yet.",
        },
        pagination: {
            previous: "Previous",
            next: "Next",
            range: "Showing {start} to {end} of {total} results",
        },
        home: {
            noPracticeWordsLeft: "No practice words left",
            noPracticeWordsDescription: "All words in this passage are already marked as familiar, so there is nothing left to practise here.",
        },
        reading: {
            author: "Author",
            startPractice: "Start practice",
            preparingPractice: "Preparing practice",
            savePassage: "Save this passage",
            removeSavedPassage: "Remove saved passage",
            previewSaveUnavailable: "Save is unavailable for preview passages",
            loginToSavePassages: "Login to save passages",
            lookup: "Lookup",
            canonical: "Canonical",
            addToWordList: "Add to word list",
            addedToWordList: "Added to word list",
            loginToAddWords: "Login to add words",
            loadingDefinition: "Loading definition...",
            noDefinition: "No definition available yet.",
            loginToViewDefinitions: "Login to view definitions.",
            failedToLoadDefinition: "Failed to load definition.",
        },
        about: {
            title: "About How To Say",
            intro: "How To Say is built for immersive vocabulary learning. It turns reading, guessing, bookmarking, and repeated exposure into one continuous workflow, so new words stay connected to real language instead of isolated lists.",
            readTitle: "Read in context",
            readDescription: "Learn through literary passages, examples, and sentence-level exposure instead of flashcards alone.",
            practiceTitle: "Practice actively",
            practiceDescription: "Move from recognition to recall with guessing flows, graded practice, and image-based prompts.",
            bankTitle: "Build your own bank",
            bankDescription: "Save words as you read, revisit them later, and keep your practice focused on what is still unfamiliar.",
            feedbackTitle: "Send feedback",
            feedbackDescription: "Share bugs, product suggestions, missing features, or anything that feels unclear.",
            feedbackPlaceholder: "Tell us what would make How To Say better...",
            feedbackThanks: "Thanks. Your feedback has been sent.",
            feedbackError: "Submission failed. Please try again.",
            feedbackSending: "Sending...",
            feedbackSubmit: "Submit feedback",
        },
        pricing: {
            eyebrow: "Plans",
            title: "Access the complete learning workflow.",
            intro: "Start free to evaluate the product, or upgrade for full access to advanced modes, deeper vocabulary coverage, and personal learning tools.",
            unlockTitle: "What Pro unlocks",
            unlockDescription: "HowToSay Pro is designed for learners who want a more structured workflow, deeper exposure, and better control over long-term vocabulary retention.",
            advancedTitle: "Advanced practice modes",
            advancedDescription: "Move beyond basic guessing with richer exercises, audio-supported prompts, and more demanding recognition-to-recall flows.",
            coverageTitle: "Deeper content coverage",
            coverageDescription: "Access broader vocabulary, more examples, and stronger sentence context for learning words in real usage rather than in isolation.",
            controlTitle: "Personal learning control",
            controlDescription: "Maintain your own word book, organize what matters, and keep reviewing with a workflow built for continuous progress.",
            requestProTitle: "Request Pro",
            requestProContent: "Please email bytegush@hotmail.com with your learning use case and expected usage.",
            requestProConfirm: "Go Back",
        },
        pricingTiers: {
            free: {
                title: "Free",
                price: "Free",
                description: "For evaluation and light daily practice.",
                features: ["Daily usage limits", "Core learning modes", "Request Pro access"],
                buttonText: "Request Pro",
            },
            pro: {
                title: "Pro",
                price: "$4/year",
                description: "For committed learners who want the full product.",
                features: [
                    "All learning modes unlocked",
                    "Advanced vocabulary and audio support",
                    "Richer sentence and example coverage",
                    "Full word book management",
                ],
                buttonText: "Buy License",
            },
            edu: {
                title: "Edu Pro",
                price: "$2/year",
                description: "For students with verified educational email access.",
                features: [
                    "All learning modes unlocked",
                    "Advanced vocabulary and audio support",
                    "Richer sentence and example coverage",
                    "Full word book management",
                ],
                buttonText: "Buy License",
            },
        },
        daily: {
            title: "Daily Guess",
            intro: "A short daily word-guess challenge with text clues and spelling practice.",
            loading: "Loading daily challenge...",
            error: "Unable to load today's words right now.",
            empty: "No daily challenge is available yet.",
        },
        assessment: {
            eyebrow: "Level Assessment",
            title: "Estimate your working vocabulary level",
            intro: "This quick assessment is meant to help you choose a useful starting level for daily practice. It is not a formal test, but it is good enough to calibrate your word flow before you begin.",
            questions: "Questions",
            quickChecks: "quick checks",
            currentLevel: "Current level",
            signInToSave: "Sign in to save",
            question: "Question",
            answered: "You answered {score} out of {total} correctly.",
            answerAll: "Answer all questions to see your suggested level.",
            seeResult: "See result",
            recommendedLevel: "Recommended level",
            recommendedDescription: "Use this as your default practice band. You can still fine-tune it later from your user menu if the words feel too easy or too dense.",
            applying: "Applying...",
            applyLevel: "Apply this level",
            signInToApply: "Sign in to apply",
            goToDaily: "Go to Daily Guess",
            saveSuccess: "Your level has been updated to {level}.",
            saveError: "Failed to update your level. Please try again.",
        },
        reviewPage: {
            eyebrow: "Progress",
            loginTitle: "See your review rhythm in one place",
            loginBody: "This page brings together your due queue, recent activity, memory profile, and the next best review action so you can keep the system healthy.",
            feature1Title: "Due queue overview",
            feature1Body: "See how many words are waiting and when it makes sense to start another review round.",
            feature2Title: "Memory profile",
            feature2Body: "Spot fragile words, stable words, and areas that still need repeated support.",
            feature3Title: "Weekly momentum",
            feature3Body: "Follow review volume, streaks, and recent additions so progress stays visible.",
            loginCta: "Login to view progress",
            title: "Learning overview",
            intro: "Track what is due, see where your memory is fragile, and jump straight into a review round when you are ready.",
            loadingBadge: "Loading...",
            wordsDue: "{count} words due",
            startReview: "Start review",
            openVocabulary: "Open vocabulary",
            loading: "Loading review dashboard...",
            statDueNow: "Due now",
            statDueNowHint: "Words waiting in your review queue",
            statLearning: "Learning",
            statLearningHint: "Words still forming stable memory",
            statInReview: "In review",
            statInReviewHint: "Words in spaced repetition rotation",
            statMastered: "Mastered",
            statMasteredHint: "Words currently pushed to long intervals",
            statAddedThisWeek: "Added this week",
            statAddedThisWeekHint: "New words entering your system",
            statReviewsToday: "Reviews today",
            statReviewsTodayHint: "{count} skipped since midnight",
            statCurrentLevel: "Current level",
            statCurrentLevelHint: "{count} day learning streak",
            activityTitle: "7-day activity",
            activityBody: "Reviews and new words across the last week.",
            reviewsBarTitle: "{count} reviews",
            addedBarTitle: "{count} added",
            memoryProfileTitle: "Memory profile",
            memoryProfileBody: "We translate the memory model into simple states so you can tell which words are fragile, stabilizing, or already long-term.",
            fragile: "Fragile",
            building: "Building",
            stable: "Stable",
            mastered: "Mastered",
            nextActionTitle: "Suggested next action",
            nextActionReview: "Your queue already has due words. Clearing those will improve spacing quality the fastest.",
            nextActionRead: "You could add fresh input, but this page now prioritizes review first so the queue stays healthy before you branch out.",
            nextActionWordbook: "Your queue is under control. You can still start a review round here, or refine your saved words in vocabulary.",
            dueNowSummary: "{count} words due now",
            streakSummary: "{count} day active streak",
            addedThisWeekSummary: "{count} words added this week",
            oftenWrongTitle: "Often wrong",
            oftenWrongBody: "Words with repeated wrong answers and rising difficulty.",
            wrongAnswers: "{count} wrong answers",
            difficulty: "Difficulty {count}",
            stability: "Stability {count}",
            noOftenWrong: "No repeated wrong-answer words yet.",
            needsHintsTitle: "Needs hints",
            needsHintsBody: "Words you usually reach with support, but have not fully internalized yet.",
            hintedCompletions: "{count} hinted completions",
            noNeedsHints: "No hint-heavy words yet.",
            mostSkippedTitle: "Most skipped",
            mostSkippedBody: "Words you are most likely to move past before solving.",
            skips: "{count} skips",
            noMostSkipped: "No skipped words recorded yet.",
        },
        literatureTimeline: {
            unknownYear: "Unknown year",
            allContent: "All literature",
            detailLoadFailed: "Unable to load this excerpt right now.",
            listLoadFailed: "Unable to load the timeline right now.",
            viewAll: "View all",
            loadingMore: "Loading...",
            loadingContent: "Loading excerpt...",
        },
        practice: {
            loadingWords: "Loading practice words...",
            loadError: "Unable to load practice words right now.",
            empty: "No practice words are available.",
        },
        toolbox: {
            removeSavedWord: "Remove from saved words",
            saveWord: "Save word",
            saved: "Saved",
            save: "Save",
            ignoreWord: "Ignore this word",
            ignore: "Ignore",
            more: "More",
            shuffle: "Shuffle",
            keyboardHelp: "Keyboard help",
            hideHelp: "Hide help",
            report: "Report",
            closePractice: "Close practice",
            keyboard: "Keyboard",
            keyboardItems: [
                { keycap: "1", label: "Hint" },
                { keycap: "2", label: "Pronounce" },
                { keycap: "Enter", label: "Reveal / Next" },
                { keycap: "<-", label: "Prev" },
                { keycap: "->", label: "Next" },
            ],
        },
        reportDialog: {
            title: "Thanks for your report",
            placeholder: "Help us improve the accuracy of this word.",
            submit: "Submit",
            cancel: "Cancel",
        },
        starRating: {
            familiarity: "Familiarity:",
            successHint: "Good job! Press <Enter> to continue.",
        },
        cardComposer: {
            createTitle: "Create a card",
            editTitle: "Edit card",
            intro: "Build cards from text, images, audio, and links. Learners will see the prompt first, then reveal the answer.",
            activeInReview: "Active in review",
            titleRequired: "Title is required.",
            blocksRequired: "Prompt and answer each need at least one filled block.",
            unableToSave: "Unable to save card.",
            titlePlaceholder: "Card title",
            saving: "Saving...",
            cancel: "Cancel",
        },
        cardBlocks: {
            imageAlt: "Card image",
            optionalIntro: "Optional blocks shown after the answer.",
            requiredIntro: "Add one or more blocks in the order learners should see them.",
            noBlocks: "No blocks yet.",
            remove: "Remove",
            textPlaceholder: "Write the prompt, answer, or note here...",
            urlPlaceholder: "{type} URL",
            linkLabelPlaceholder: "Link label",
            captionPlaceholder: "Caption",
            types: {
                text: "text",
                image: "image",
                audio: "audio",
                link: "link",
            },
        },
        deckDetail: {
            loginTitle: "Login to manage this deck",
            loginBody: "Deck pages let you edit the deck itself, create cards with multiple content blocks, and control which cards stay active in review.",
            loginCta: "Login to continue",
            loading: "Loading deck...",
            unableToLoad: "Unable to load this deck.",
            backToCards: "Back to cards",
            reviewThisDeck: "Review this deck",
            eyebrow: "Deck",
            deckStats: "{cards} cards · {due} due now · {newCards} still new",
            archiveDeck: "Archive deck",
            unarchiveDeck: "Unarchive deck",
            deleteDeck: "Delete deck",
            deckNameRequired: "Deck name is required.",
            unableToLoadDeck: "Unable to load deck.",
            unableToSaveDeck: "Unable to save deck.",
            unableToUpdateArchive: "Unable to update archive status.",
            deleteDeckConfirm: "Delete \"{name}\" and all of its cards?",
            unableToDeleteDeck: "Unable to delete deck.",
            unableToCreateCard: "Unable to create card.",
            unableToUpdateCard: "Unable to update card.",
            deleteCardConfirm: "Delete this card?",
            unableToDeleteCard: "Unable to delete card.",
            deckNamePlaceholder: "Deck name",
            deckDescriptionPlaceholder: "What does this deck cover?",
            savingDeck: "Saving...",
            saveDeck: "Save deck",
            createCard: "Create card",
            saveCard: "Save card",
            cardsInDeck: "Cards in this deck",
            cardsInDeckBody: "Edit existing cards inline, or turn them off without deleting the whole deck.",
            noCards: "No cards yet. Create your first card above.",
            statusNew: "new",
            statusActive: "active",
            statusPaused: "paused",
            edit: "Edit",
            delete: "Delete",
            prompt: "Prompt",
            answer: "Answer",
            notes: "Notes",
        },
        customPractice: {
            emptyContent: "The content is empty.",
            placeholder: "Paste a word list to practise...",
            attachFile: "Attach a file",
            practise: "Practise",
        },
        videoDemo: {
            title: "More features on Pro",
        },
        helpPanel: {
            title: "Keyboard Shortcuts",
            closePanel: "Close panel",
            items: [
                { keycap: "1", label: "Hint" },
                { keycap: "2", label: "Pronounce" },
                { keycap: "3", label: "Reveal" },
                { keycap: "4", label: "Next" },
            ],
        },
        wordSlideOver: {
            title: "Word list",
            closePanel: "Close panel",
        },
        activation: {
            title: "Activate Pro",
            invalidLicense: "Invalid License: {reason}",
            license: "License",
            placeholder: "xxxxx-xxxxx-xxxxx-xxxxx",
            activate: "Activate",
            buyLicense: "Buy License",
        },
    },
    zh: {
        nav: {
            literature: "文学",
            vocabulary: "词汇",
            progress: "进度",
            cards: "卡片",
            pricing: "定价",
            title: "How To Say",
            tagline: "语言的边界，就是世界的边界。",
        },
        menu: {
            openToolsMenu: "打开菜单",
            quickSearch: "快捷查词",
            cardsPreview: "卡片",
            previewTag: "预览",
            savedLiterature: "收藏文学",
            dailyGuess: "每日猜词",
            imageMode: "看图模式",
            gradingExercise: "分级练习",
            chromeExtension: "Chrome 扩展",
            about: "关于",
            appearance: "外观",
            language: "语言",
            darkMode: "夜间",
            lightMode: "白天",
            english: "English",
            chinese: "中文",
            japanese: "日本語",
            korean: "한국어",
        },
        auth: {
            loading: "加载中...",
            signIn: "登录",
            level: "等级",
            assessYourLevel: "测试你的等级",
            signOut: "退出登录",
            expireAt: "到期时间",
        },
        search: {
            open: "打开快捷查词",
            title: "快捷查词",
            description: "不用离开当前页面，直接查询单词释义。",
            shortcutHint: "快捷键：/ 或 Ctrl/Cmd + K",
            placeholder: "输入单词",
            submit: "查询",
            searching: "查询中...",
            empty: "输入一个单词即可查看释义。",
            notFound: "没有找到这个单词。",
            examples: "例句",
            phonetic: "音标",
            definition: "释义",
            close: "关闭",
            chinese: "中文",
        },
        common: {
            backHome: "返回首页",
            backToLiterature: "返回文学",
            archived: "已归档",
            noDescription: "暂时还没有描述。",
            cancel: "取消",
        },
        savedLiterature: {
            title: "收藏文学",
            intro: "这里会收纳你在首页点过收藏的文学片段，作为一个自己的阅读书架。",
            loginTitle: "登录后查看收藏文学",
            loginBody: "收藏文章和你的账户绑定，所以需要先登录才能加载你的阅读书架。",
            loginCta: "登录继续",
            loading: "正在加载收藏文章...",
            emptyTitle: "还没有收藏文章",
            emptyBody: "当你在首页收藏文学片段后，它会出现在这里。",
            savedCount: "共收藏 {count} 篇",
            openLiterature: "浏览文学",
        },
        cards: {
            title: "卡片",
            marketingTitle: "把真正遇到的词做成可复习的卡片组。",
            marketingBody: "把阅读和查词沉淀成可重复使用的复习系统。创建卡组、收集难词，让间隔复习始终贴着你的真实材料。",
            feature1Title: "建立聚焦卡组",
            feature1Body: "按考试、文学或主题拆分卡组，而不是把所有内容混在一起。",
            feature2Title: "优先复习到期内容",
            feature2Body: "随时看到现在最该复习的部分，让单次复习更短、更稳定。",
            feature3Title: "保持语境联系",
            feature3Body: "卡片最好来自你已经读过的句子和文章，而不是孤立条目。",
            loginCta: "登录后使用卡片",
            decksTitle: "你的卡组工作台",
            decksBody: "创建小而清晰的卡组，关注到期量，在合适的时候直接进入复习。",
            statsDecks: "卡组数",
            statsCards: "卡片数",
            statsDueNow: "当前到期",
            openReview: "开始复习",
            createDeckTitle: "创建新卡组",
            createDeckBody: "尽量用简短明确的名字，让卡组长期保持可用。",
            deckName: "卡组名称",
            deckDescription: "卡组描述",
            createDeck: "创建卡组",
            creatingDeck: "创建中...",
            createDeckFailed: "创建卡组失败。",
            libraryTitle: "卡组列表",
            libraryBody: "打开卡组后可以添加卡片、查看到期量并检查内容。",
            loadingDecks: "正在加载卡组...",
            emptyDecks: "还没有卡组，先在上面创建一个。",
            loadDecksFailed: "加载卡组失败。",
            cardsCount: "{count} 张卡片",
            dueCount: "{count} 张到期",
            newCount: "{count} 张新卡",
        },
        cardsReview: {
            title: "卡片复习",
            marketingTitle: "按记忆节奏复习你保存的任意主题",
            marketingBody: "卡片复习中心会汇总各卡组已到期的卡片，让你逐张翻看，再按类似 Anki 的方式给回忆打分。",
            statDueNow: "当前到期",
            statOverdue: "已逾期",
            statDueToday: "今日到期",
            statNewCards: "新卡片",
            statDueNowBody: "先看到现在最需要处理的内容。",
            statOverdueBody: "识别已经超过理想复习间隔的卡片。",
            statDeckFilterBody: "可以只看单个卡组，也可以清空筛选查看混合队列。",
            deckFilter: "卡组筛选",
            loginCta: "登录后复习卡片",
            backToCards: "返回卡片",
            queueTitle: "自定义卡组的记忆队列",
            queueBody: "先看现在到期的内容，了解逾期压力，然后开始一轮自我评分复习。",
            allDecks: "所有卡组",
            startReview: "开始复习",
            loadingCenter: "正在加载卡片复习中心...",
            decksWithDueCards: "有到期卡片的卡组",
            noDueCards: "当前没有到期卡片。",
            cardsCount: "{count} 张卡片",
            newCount: "{count} 张新卡",
            dueCount: "{count} 张到期",
            overdueCount: "{count} 张逾期",
            currentRoundPreview: "当前轮次预览",
            filteredToOneDeck: "当前队列只显示这个卡组。",
            blendedQueue: "当前队列混合了所有已到期卡组。",
            cardsLabel: "卡片",
            noCardsInFilter: "这个筛选下没有到期卡片。",
            nothingReady: "暂时没有可复习内容。",
            continue: "继续",
            noCardsLeft: "这一轮已经没有卡片了。",
            backToCenter: "返回复习中心",
            closeRound: "关闭本轮",
            prompt: "题面",
            answer: "答案",
            revealHelp: "准备好评分时再展开答案。",
            notes: "备注",
            revealAnswer: "显示答案",
            again: "重来",
            hard: "困难",
            good: "良好",
            easy: "简单",
            unableToLoad: "无法加载卡片复习。",
            unableToSave: "无法保存复习结果。",
            cardProgress: "第 {current} / {total} 张 · {badge}",
            badges: {
                new: "新卡",
                learning: "学习中",
                review: "复习中",
                mastered: "已掌握",
                fragile: "脆弱",
                building: "建立中",
                stable: "稳定",
            },
        },
        vocabulary: {
            title: "你的词汇库",
            description: "查看已保存单词，按熟悉度过滤，并随时把这些词转成主动练习。",
            feature1Title: "保存真正有用的词",
            feature1Body: "把阅读、练习和查词过程中遇到的单词集中到一个地方。",
            feature2Title: "按记忆状态过滤",
            feature2Body: "把脆弱词和稳定词分开，让复习时间用在真正需要的地方。",
            feature3Title: "从自己的词表练习",
            feature3Body: "直接从你已经收集的词汇开始训练，而不是重新找材料。",
            loginCta: "登录后打开词汇库",
            library: "词汇库",
            memoryFilter: "筛选：{label}",
            searchPlaceholder: "搜索已保存单词",
            importWords: "导入单词",
            practise: "练习",
            practiseSavedWords: "练习已保存单词",
            openCustomPractise: "打开自定义练习",
        },
        listMenu: {
            allWords: "全部单词",
            unfamiliar: "不熟悉",
            familiarity1: "熟悉度 1",
            familiarity2: "熟悉度 2",
            familiarity3: "熟悉度 3",
            familiarity4: "熟悉度 4",
            familiarity5: "熟悉度 5",
            ignored: "已忽略",
        },
        inputModal: {
            title: "导入单词",
            placeholder: "把单词粘贴到这里，支持空格、逗号或换行分隔。",
            confirm: "导入",
            cancel: "取消",
        },
        wordBook: {
            word: "单词",
            memory: "记忆状态",
            familiarity: "熟悉度",
            query: "查询次数",
            actions: "操作",
            definition: "释义",
            loadingDefinition: "正在加载释义...",
            fragile: "脆弱",
            building: "建立中",
            stable: "稳定",
            mastered: "掌握",
            untracked: "未跟踪",
            ignoreWord: "忽略单词",
            listenOnYouGlish: "在 YouGlish 收听",
            removeWord: "删除单词",
            empty: "还没有保存任何单词。",
        },
        pagination: {
            previous: "上一页",
            next: "下一页",
            range: "显示第 {start} 到 {end} 条，共 {total} 条",
        },
        home: {
            noPracticeWordsLeft: "没有可练习的单词了",
            noPracticeWordsDescription: "这篇文章里的词都已经比较熟悉了，这里暂时没有需要继续练习的内容。",
        },
        reading: {
            author: "作者",
            startPractice: "开始练习",
            preparingPractice: "正在准备练习",
            savePassage: "收藏这篇文章",
            removeSavedPassage: "取消收藏",
            previewSaveUnavailable: "预览文章暂不支持收藏",
            loginToSavePassages: "登录后可收藏文章",
            lookup: "释义",
            canonical: "词元",
            addToWordList: "加入词库",
            addedToWordList: "已加入词库",
            loginToAddWords: "登录后可加入词库",
            loadingDefinition: "正在加载释义...",
            noDefinition: "暂时还没有释义。",
            loginToViewDefinitions: "登录后可查看释义。",
            failedToLoadDefinition: "释义加载失败。",
        },
        about: {
            title: "关于 How To Say",
            intro: "How To Say 专注于沉浸式词汇学习。它把阅读、猜词、收藏和重复暴露串成一个连续流程，让新词始终和真实语境绑定，而不是停留在孤立的词表里。",
            readTitle: "在语境中阅读",
            readDescription: "通过文学片段、例句和句子级输入来学习，而不是只靠抽认卡。",
            practiceTitle: "主动练习",
            practiceDescription: "用猜词流程、分级练习和图片提示，把认识推进到真正能回忆出来。",
            bankTitle: "建立自己的词库",
            bankDescription: "边读边收词，之后随时回看，让练习始终聚焦在你还不熟悉的部分。",
            feedbackTitle: "发送反馈",
            feedbackDescription: "欢迎提交 bug、产品建议、缺失功能，或任何让你感到不清晰的地方。",
            feedbackPlaceholder: "告诉我们，什么能让 How To Say 更好用...",
            feedbackThanks: "感谢反馈，已经发送成功。",
            feedbackError: "提交失败，请稍后再试。",
            feedbackSending: "发送中...",
            feedbackSubmit: "提交反馈",
        },
        pricing: {
            eyebrow: "方案",
            title: "解锁完整学习工作流。",
            intro: "你可以先免费体验，再根据需要升级，获得更完整的高级练习、更深的词汇覆盖和个人学习管理能力。",
            unlockTitle: "Pro 能解锁什么",
            unlockDescription: "HowToSay Pro 面向希望获得更强结构感、更深输入和更好长期记忆控制的学习者。",
            advancedTitle: "更高级的练习模式",
            advancedDescription: "不再停留在基础猜词，加入更丰富的题型、音频辅助和更高强度的识别到回忆训练。",
            coverageTitle: "更深的内容覆盖",
            coverageDescription: "获得更广的词汇、更多例句和更强的上下文支持，让单词学习更贴近真实用法。",
            controlTitle: "更完整的个人学习控制",
            controlDescription: "维护自己的单词本，组织真正重要的内容，并用连续工作流持续复习。",
            requestProTitle: "申请 Pro",
            requestProContent: "请发送邮件到 bytegush@hotmail.com，说明你的学习场景和预期使用方式。",
            requestProConfirm: "返回",
        },
        pricingTiers: {
            free: {
                title: "免费版",
                price: "免费",
                description: "适合体验产品和轻量日常练习。",
                features: ["每日使用限制", "核心学习模式", "可申请 Pro 访问"],
                buttonText: "申请 Pro",
            },
            pro: {
                title: "Pro",
                price: "$4/年",
                description: "适合想完整使用产品的长期学习者。",
                features: [
                    "解锁全部学习模式",
                    "高级词汇与音频支持",
                    "更丰富的句子与例句覆盖",
                    "完整的词书管理能力",
                ],
                buttonText: "购买许可",
            },
            edu: {
                title: "教育版 Pro",
                price: "$2/年",
                description: "适合拥有教育邮箱认证的学生。",
                features: [
                    "解锁全部学习模式",
                    "高级词汇与音频支持",
                    "更丰富的句子与例句覆盖",
                    "完整的词书管理能力",
                ],
                buttonText: "购买许可",
            },
        },
        daily: {
            title: "每日猜词",
            intro: "一个简短的每日猜词挑战，结合文本线索和拼写练习。",
            loading: "正在加载今日挑战...",
            error: "暂时无法加载今天的单词。",
            empty: "今天的每日挑战还没有准备好。",
        },
        assessment: {
            eyebrow: "词汇等级测试",
            title: "估算你的实用词汇等级",
            intro: "这个小测试可以帮助你选择更合适的起始练习等级。它不是正式考试，但足以在开始前帮你校准词汇强度。",
            questions: "题目数",
            quickChecks: "个快速判断",
            currentLevel: "当前等级",
            signInToSave: "登录后可保存",
            question: "题目",
            answered: "你答对了 {score} / {total} 题。",
            answerAll: "答完所有题目后即可查看建议等级。",
            seeResult: "查看结果",
            recommendedLevel: "推荐等级",
            recommendedDescription: "可以先把它当成默认练习档位。如果觉得太简单或太密集，之后仍然可以在用户菜单里微调。",
            applying: "应用中...",
            applyLevel: "应用这个等级",
            signInToApply: "登录后应用",
            goToDaily: "去每日猜词",
            saveSuccess: "你的等级已更新为 {level}。",
            saveError: "更新等级失败，请稍后再试。",
        },
        reviewPage: {
            eyebrow: "进度",
            loginTitle: "在一个页面里看到你的复习节奏",
            loginBody: "这里会汇总待复习队列、近期活动、记忆状态和下一步建议，帮助你把整个系统维持在健康区间。",
            feature1Title: "待复习总览",
            feature1Body: "先看有多少词在等待，以及现在是不是适合开始一轮复习。",
            feature2Title: "记忆画像",
            feature2Body: "快速识别脆弱词、稳定词，以及仍然需要反复支持的部分。",
            feature3Title: "每周势头",
            feature3Body: "持续观察复习量、连续天数和新增词汇，让进展始终可见。",
            loginCta: "登录后查看进度",
            title: "学习总览",
            intro: "查看哪些内容已经到期，找出记忆最脆弱的部分，并在合适的时候直接开始一轮复习。",
            loadingBadge: "加载中...",
            wordsDue: "{count} 个单词待复习",
            startReview: "开始复习",
            openVocabulary: "打开词汇库",
            loading: "正在加载复习面板...",
            statDueNow: "当前到期",
            statDueNowHint: "正在等待进入复习队列的单词",
            statLearning: "学习中",
            statLearningHint: "还在形成稳定记忆的单词",
            statInReview: "复习中",
            statInReviewHint: "已经进入间隔复习循环的单词",
            statMastered: "已掌握",
            statMasteredHint: "当前已推到更长间隔的单词",
            statAddedThisWeek: "本周新增",
            statAddedThisWeekHint: "最近进入系统的新单词",
            statReviewsToday: "今日复习",
            statReviewsTodayHint: "今天凌晨后跳过了 {count} 次",
            statCurrentLevel: "当前等级",
            statCurrentLevelHint: "连续学习 {count} 天",
            activityTitle: "7 天活动",
            activityBody: "过去一周里的复习量和新增量。",
            reviewsBarTitle: "{count} 次复习",
            addedBarTitle: "{count} 个新增",
            memoryProfileTitle: "记忆画像",
            memoryProfileBody: "我们把记忆模型翻译成更直观的状态，方便你快速判断哪些词脆弱、哪些正在稳定、哪些已经进入长期记忆。",
            fragile: "脆弱",
            building: "建立中",
            stable: "稳定",
            mastered: "掌握",
            nextActionTitle: "建议的下一步",
            nextActionReview: "你的队列里已经有到期内容。优先清掉这些，会最快改善复习间隔的质量。",
            nextActionRead: "你可以继续补充输入，但这个页面现在会优先建议先复习，确保队列健康之后再继续扩展。",
            nextActionWordbook: "你的队列目前比较轻松。你可以继续在这里复习，也可以回到词汇库精修已保存内容。",
            dueNowSummary: "当前有 {count} 个单词到期",
            streakSummary: "已连续活跃 {count} 天",
            addedThisWeekSummary: "本周新增了 {count} 个单词",
            oftenWrongTitle: "经常答错",
            oftenWrongBody: "这些词重复答错，难度也在逐渐上升。",
            wrongAnswers: "答错 {count} 次",
            difficulty: "难度 {count}",
            stability: "稳定度 {count}",
            noOftenWrong: "暂时还没有重复答错很多次的单词。",
            needsHintsTitle: "依赖提示",
            needsHintsBody: "这些词通常需要辅助才能答出，还没有真正内化。",
            hintedCompletions: "借助提示完成 {count} 次",
            noNeedsHints: "暂时还没有明显依赖提示的单词。",
            mostSkippedTitle: "最常跳过",
            mostSkippedBody: "这些词是你最容易先跳过去、暂时不解的部分。",
            skips: "跳过 {count} 次",
            noMostSkipped: "暂时还没有跳过记录较多的单词。",
        },
        literatureTimeline: {
            unknownYear: "未知年代",
            allContent: "全部文学内容",
            detailLoadFailed: "暂时无法加载这段内容，请稍后重试。",
            listLoadFailed: "暂时无法加载时间线，请稍后重试。",
            viewAll: "查看全部",
            loadingMore: "加载中...",
            loadingContent: "正在加载内容",
        },
        practice: {
            loadingWords: "正在加载练习单词...",
            loadError: "暂时无法加载练习单词。",
            empty: "当前没有可练习的单词。",
        },
        toolbox: {
            removeSavedWord: "从已保存单词中移除",
            saveWord: "保存这个单词",
            saved: "已保存",
            save: "保存",
            ignoreWord: "忽略这个单词",
            ignore: "忽略",
            more: "更多",
            shuffle: "打乱顺序",
            keyboardHelp: "键盘帮助",
            hideHelp: "收起帮助",
            report: "反馈问题",
            closePractice: "关闭练习",
            keyboard: "键盘",
            keyboardItems: [
                { keycap: "1", label: "提示" },
                { keycap: "2", label: "发音" },
                { keycap: "Enter", label: "揭晓 / 下一个" },
                { keycap: "<-", label: "上一个" },
                { keycap: "->", label: "下一个" },
            ],
        },
        reportDialog: {
            title: "感谢你的反馈",
            placeholder: "告诉我们这个单词哪里不准确，帮助我们继续改进。",
            submit: "提交",
            cancel: "取消",
        },
        starRating: {
            familiarity: "熟悉度：",
            successHint: "做得不错，按 <Enter> 继续。",
        },
        cardComposer: {
            createTitle: "创建卡片",
            editTitle: "编辑卡片",
            intro: "你可以用文本、图片、音频和链接来搭建卡片。学习者会先看到题面，再决定何时揭晓答案。",
            activeInReview: "在复习中启用",
            titleRequired: "卡片标题不能为空。",
            blocksRequired: "题面和答案都至少需要一个已填写的内容块。",
            unableToSave: "无法保存卡片。",
            titlePlaceholder: "卡片标题",
            saving: "保存中...",
            cancel: "取消",
        },
        cardBlocks: {
            imageAlt: "卡片图片",
            optionalIntro: "可选内容块会在答案之后展示。",
            requiredIntro: "按学习者应看到的顺序添加一个或多个内容块。",
            noBlocks: "还没有内容块。",
            remove: "移除",
            textPlaceholder: "在这里填写题面、答案或备注...",
            urlPlaceholder: "{type} 地址",
            linkLabelPlaceholder: "链接文字",
            captionPlaceholder: "说明文字",
            types: {
                text: "文本",
                image: "图片",
                audio: "音频",
                link: "链接",
            },
        },
        deckDetail: {
            loginTitle: "登录后管理这个卡组",
            loginBody: "在卡组详情页里，你可以编辑卡组本身、创建多内容块卡片，并控制哪些卡片继续参与复习。",
            loginCta: "登录继续",
            loading: "正在加载卡组...",
            unableToLoad: "暂时无法加载这个卡组。",
            backToCards: "返回卡片",
            reviewThisDeck: "复习这个卡组",
            eyebrow: "卡组",
            deckStats: "{cards} 张卡片 · {due} 张当前到期 · {newCards} 张仍是新卡",
            archiveDeck: "归档卡组",
            unarchiveDeck: "取消归档",
            deleteDeck: "删除卡组",
            deckNameRequired: "卡组名称不能为空。",
            unableToLoadDeck: "无法加载卡组。",
            unableToSaveDeck: "无法保存卡组。",
            unableToUpdateArchive: "无法更新归档状态。",
            deleteDeckConfirm: "删除「{name}」以及它的所有卡片吗？",
            unableToDeleteDeck: "无法删除卡组。",
            unableToCreateCard: "无法创建卡片。",
            unableToUpdateCard: "无法更新卡片。",
            deleteCardConfirm: "要删除这张卡片吗？",
            unableToDeleteCard: "无法删除卡片。",
            deckNamePlaceholder: "卡组名称",
            deckDescriptionPlaceholder: "这个卡组主要覆盖什么内容？",
            savingDeck: "保存中...",
            saveDeck: "保存卡组",
            createCard: "创建卡片",
            saveCard: "保存卡片",
            cardsInDeck: "这个卡组里的卡片",
            cardsInDeckBody: "你可以直接在这里编辑已有卡片，或者停用它们，而不必删除整个卡组。",
            noCards: "还没有卡片，先在上面创建第一张吧。",
            statusNew: "新卡",
            statusActive: "启用中",
            statusPaused: "已暂停",
            edit: "编辑",
            delete: "删除",
            prompt: "题面",
            answer: "答案",
            notes: "备注",
        },
        customPractice: {
            emptyContent: "内容不能为空。",
            placeholder: "粘贴要练习的单词列表...",
            attachFile: "附加文件",
            practise: "开始练习",
        },
        videoDemo: {
            title: "Pro 还有更多能力",
        },
        helpPanel: {
            title: "键盘快捷键",
            closePanel: "关闭面板",
            items: [
                { keycap: "1", label: "提示" },
                { keycap: "2", label: "发音" },
                { keycap: "3", label: "揭晓" },
                { keycap: "4", label: "下一个" },
            ],
        },
        wordSlideOver: {
            title: "单词列表",
            closePanel: "关闭面板",
        },
        activation: {
            title: "激活 Pro",
            invalidLicense: "许可无效：{reason}",
            license: "许可码",
            placeholder: "xxxxx-xxxxx-xxxxx-xxxxx",
            activate: "激活",
            buyLicense: "购买许可",
        },
    },
    ja: {} as Dictionary,
    ko: {} as Dictionary,
}

function isObjectRecord(value: unknown): value is Record<string, any> {
    return typeof value === "object" && value !== null && !Array.isArray(value)
}

function mergeDictionary(base: Dictionary, overrides: Dictionary): Dictionary {
    const next: Dictionary = { ...base }

    for (const [key, value] of Object.entries(overrides)) {
        if (Array.isArray(value)) {
            next[key] = value
            continue
        }

        if (isObjectRecord(value) && isObjectRecord(base[key])) {
            next[key] = mergeDictionary(base[key], value)
            continue
        }

        next[key] = value
    }

    return next
}

export function normalizeLocale(locale?: string | null): Locale {
    const normalized = (locale || "").toLowerCase()

    if (normalized.startsWith("zh")) {
        return "zh"
    }

    if (normalized.startsWith("ja")) {
        return "ja"
    }

    if (normalized.startsWith("ko")) {
        return "ko"
    }

    return "en"
}

export function getDocumentLang(locale: Locale): string {
    if (locale === "zh") {
        return "zh-CN"
    }

    if (locale === "ja") {
        return "ja"
    }

    if (locale === "ko") {
        return "ko"
    }

    return "en"
}

dictionaries.ja = mergeDictionary(dictionaries.en, {
    nav: {
        literature: "文学",
        vocabulary: "語彙",
        progress: "進捗",
        pricing: "料金",
        tagline: "言語の境界が、世界の輪郭をつくる。",
    },
    menu: {
        openToolsMenu: "ツールメニューを開く",
        quickSearch: "クイック検索",
        cardsPreview: "カード",
        previewTag: "Preview",
        savedLiterature: "保存した文学",
        dailyGuess: "デイリークイズ",
        imageMode: "画像モード",
        gradingExercise: "レベル練習",
        chromeExtension: "Chrome 拡張",
        about: "About",
        appearance: "表示",
        language: "言語",
        darkMode: "ダーク",
        lightMode: "ライト",
        english: "English",
        chinese: "中文",
        japanese: "日本語",
        korean: "한국어",
    },
    auth: {
        loading: "読み込み中...",
        signIn: "ログイン",
        level: "レベル",
        assessYourLevel: "レベル診断",
        signOut: "ログアウト",
        expireAt: "有効期限",
    },
    search: {
        open: "クイック検索を開く",
        title: "クイック単語検索",
        description: "ページを離れずに単語を検索します。",
        shortcutHint: "ショートカット: / または Ctrl/Cmd + K",
        placeholder: "単語を入力",
        submit: "検索",
        searching: "検索中...",
        empty: "単語を検索すると意味が表示されます。",
        notFound: "その単語は見つかりませんでした。",
        examples: "例文",
        phonetic: "発音",
        definition: "定義",
        close: "閉じる",
        chinese: "中国語",
    },
    common: {
        backHome: "ホームへ戻る",
        backToLiterature: "文学へ戻る",
        archived: "アーカイブ済み",
        noDescription: "説明はまだありません。",
        cancel: "キャンセル",
    },
    savedLiterature: {
        title: "保存した文学",
        intro: "ホームで保存した文学の抜粋をまとめて見られる読書棚です。",
        loginTitle: "保存した文学を見るにはログインしてください",
        loginBody: "保存した抜粋はアカウントに紐づいているため、読書棚を読み込む前にログインが必要です。",
        loginCta: "ログインして続行",
        loading: "保存した抜粋を読み込み中...",
        emptyTitle: "まだ保存した抜粋はありません",
        emptyBody: "ホームで文学の抜粋を保存すると、ここに表示されます。",
        savedCount: "{count} 件保存済み",
        openLiterature: "文学を閲覧",
    },
    cards: {
        title: "カード",
        marketingTitle: "実際に出会った単語からデッキを作成。",
        marketingBody: "読書と検索を、繰り返し使える復習システムに変えます。デッキを作り、難しい単語を集め、自分の教材に結びついた間隔反復を続けましょう。",
        feature1Title: "集中できるデッキを作る",
        feature1Body: "試験語彙、文学、テーマ別カードを分けて管理できます。",
        feature2Title: "期限が来たものから復習",
        feature2Body: "今注意すべきカードを見つけ、短く安定した復習を続けられます。",
        feature3Title: "文脈を保つ",
        feature3Body: "カードは、読んだ文章や出会った例文から作るほど効果的です。",
        loginCta: "ログインしてカードを開く",
        decksTitle: "デッキ管理",
        decksBody: "小さく集中したデッキを作り、期限切れの量を確認し、準備ができたらすぐ復習できます。",
        statsDecks: "デッキ",
        statsCards: "カード",
        statsDueNow: "今すぐ復習",
        openReview: "復習を開く",
        createDeckTitle: "新しいデッキを作成",
        createDeckBody: "短く具体的な名前にすると、長く使いやすくなります。",
        deckName: "デッキ名",
        deckDescription: "説明",
        createDeck: "デッキを作成",
        creatingDeck: "作成中...",
        createDeckFailed: "デッキの作成に失敗しました。",
        libraryTitle: "デッキ一覧",
        libraryBody: "デッキを開いてカード追加、期限確認、内容レビューができます。",
        loadingDecks: "デッキを読み込み中...",
        emptyDecks: "まだデッキがありません。上で最初のデッキを作成してください。",
        loadDecksFailed: "デッキの読み込みに失敗しました。",
        cardsCount: "{count} 枚",
        dueCount: "{count} 枚期限到来",
        newCount: "{count} 枚新規",
    },
    cardsReview: {
        title: "カード復習",
        loginCta: "ログインしてカードを復習",
        backToCards: "カードへ戻る",
        queueTitle: "カスタムデッキの記憶キュー",
        queueBody: "今復習すべきカードを確認し、負荷を見てから自己採点の復習を始めましょう。",
        allDecks: "すべてのデッキ",
        startReview: "復習開始",
        loadingCenter: "カード復習センターを読み込み中...",
        decksWithDueCards: "期限が来たデッキ",
        noDueCards: "今は期限の来たカードがありません。",
        currentRoundPreview: "現在のラウンド",
        filteredToOneDeck: "このキューは1つのデッキに絞られています。",
        blendedQueue: "このキューは期限到来のデッキをまとめて表示します。",
        cardsLabel: "カード",
        noCardsInFilter: "この条件では期限到来カードがありません。",
        nothingReady: "まだ復習できるカードはありません。",
        continue: "続ける",
        noCardsLeft: "このラウンドのカードはありません。",
        backToCenter: "復習センターへ戻る",
        closeRound: "ラウンドを閉じる",
        prompt: "表面",
        answer: "答え",
        revealHelp: "採点する準備ができたら答えを表示してください。",
        notes: "メモ",
        revealAnswer: "答えを表示",
        again: "もう一度",
        hard: "難しい",
        good: "良い",
        easy: "簡単",
        unableToLoad: "カード復習を読み込めませんでした。",
        unableToSave: "復習結果を保存できませんでした。",
        cardProgress: "{current}/{total} 枚目 · {badge}",
        badges: {
            new: "新規",
            learning: "学習中",
            review: "復習中",
            mastered: "習得済み",
            fragile: "不安定",
            building: "構築中",
            stable: "安定",
        },
    },
    vocabulary: {
        title: "語彙ライブラリ",
        description: "保存した単語を見直し、記憶状態で絞り込み、いつでも練習に変えられます。",
        feature1Title: "役立つ単語を保存",
        feature1Body: "読書、練習、検索で出会った単語を1か所にまとめます。",
        feature2Title: "記憶状態で絞り込む",
        feature2Body: "不安定な単語と安定した単語を分け、復習時間を重要なところに集中できます。",
        feature3Title: "自分の単語で練習",
        feature3Body: "集めた語彙から直接トレーニングできます。",
        loginCta: "ログインして語彙を開く",
        library: "語彙",
        memoryFilter: "フィルター: {label}",
        searchPlaceholder: "保存した単語を検索",
        importWords: "単語を取り込む",
        practise: "練習",
        practiseSavedWords: "保存した単語を練習",
        openCustomPractise: "カスタム練習を開く",
    },
    listMenu: {
        allWords: "すべての単語",
        unfamiliar: "不慣れ",
        familiarity1: "親密度 1",
        familiarity2: "親密度 2",
        familiarity3: "親密度 3",
        familiarity4: "親密度 4",
        familiarity5: "親密度 5",
        ignored: "無視済み",
    },
    inputModal: {
        title: "単語を取り込む",
        placeholder: "単語を貼り付けてください。スペース、カンマ、改行で区切れます。",
        confirm: "取り込む",
        cancel: "キャンセル",
    },
    wordBook: {
        word: "単語",
        memory: "記憶状態",
        familiarity: "親密度",
        query: "検索回数",
        actions: "操作",
        definition: "定義",
        loadingDefinition: "定義を読み込み中...",
        fragile: "不安定",
        building: "構築中",
        stable: "安定",
        mastered: "習得済み",
        untracked: "未追跡",
        ignoreWord: "単語を無視",
        listenOnYouGlish: "YouGlish で聞く",
        removeWord: "単語を削除",
        empty: "保存した単語はまだありません。",
    },
    pagination: {
        previous: "前へ",
        next: "次へ",
        range: "{start} - {end} / {total} 件を表示",
    },
    home: {
        noPracticeWordsLeft: "練習できる単語がありません",
        noPracticeWordsDescription: "この文章の単語はすでに慣れているため、今は追加の練習対象がありません。",
    },
    reading: {
        author: "著者",
        startPractice: "練習を始める",
        preparingPractice: "練習を準備中",
        savePassage: "この文章を保存",
        removeSavedPassage: "保存を解除",
        previewSaveUnavailable: "プレビュー文章は保存できません",
        loginToSavePassages: "文章を保存するにはログインしてください",
        lookup: "意味",
        canonical: "原形",
        addToWordList: "語彙に追加",
        addedToWordList: "語彙に追加済み",
        loginToAddWords: "単語を追加するにはログインしてください",
        loadingDefinition: "定義を読み込み中...",
        noDefinition: "まだ定義がありません。",
        loginToViewDefinitions: "定義を見るにはログインしてください。",
        failedToLoadDefinition: "定義の読み込みに失敗しました。",
    },
    about: {
        title: "How To Say について",
        intro: "How To Say は没入型の語彙学習のために作られました。読書、推測、保存、繰り返し接触を1つの流れにし、新しい単語を実際の言語文脈と結びつけます。",
        readTitle: "文脈で読む",
        readDescription: "文学の抜粋や例文を通して単語を学びます。",
        practiceTitle: "能動的に練習",
        practiceDescription: "推測、レベル別練習、画像ヒントで認識から想起へ進みます。",
        bankTitle: "自分の語彙庫を作る",
        bankDescription: "読みながら単語を保存し、後で見直して、まだ不安定な語彙に集中できます。",
        feedbackTitle: "フィードバックを送る",
        feedbackDescription: "バグや改善案、分かりにくい点を送ってください。",
        feedbackPlaceholder: "How To Say をより良くするためのご意見を教えてください...",
        feedbackThanks: "ありがとうございます。送信しました。",
        feedbackError: "送信に失敗しました。後でもう一度お試しください。",
        feedbackSending: "送信中...",
        feedbackSubmit: "送信",
    },
    pricing: {
        eyebrow: "プラン",
        title: "学習ワークフロー全体を解放。",
        intro: "まずは無料で試し、必要に応じて高度なモードや深い語彙サポートへアップグレードできます。",
        unlockTitle: "Pro で解放されるもの",
        unlockDescription: "HowToSay Pro は、より構造的で長期的な語彙管理を求める学習者向けです。",
        advancedTitle: "高度な練習モード",
        advancedDescription: "より豊かな問題形式、音声補助、認識から想起までの強い練習を提供します。",
        coverageTitle: "より深いコンテンツ",
        coverageDescription: "語彙、例文、文脈の幅が広がり、実際の用法に近い学習ができます。",
        controlTitle: "学習管理の強化",
        controlDescription: "自分の語彙帳を保ち、重要なものを整理し、継続的に復習できます。",
        requestProTitle: "Pro を申請",
        requestProContent: "学習用途と想定利用について bytegush@hotmail.com までメールしてください。",
        requestProConfirm: "戻る",
    },
    pricingTiers: {
        free: {
            title: "無料",
            price: "無料",
            description: "評価と軽い日常練習向け。",
            features: ["1日の使用制限", "基本学習モード", "Pro 利用申請"],
            buttonText: "Pro を申請",
        },
        pro: {
            title: "Pro",
            price: "$4/年",
            description: "製品をしっかり活用したい学習者向け。",
            features: ["すべての学習モードを解放", "高度な語彙と音声サポート", "より豊富な文と例文", "完全な語彙管理"],
            buttonText: "ライセンスを購入",
        },
        edu: {
            title: "Edu Pro",
            price: "$2/年",
            description: "教育用メール認証済みの学生向け。",
            features: ["すべての学習モードを解放", "高度な語彙と音声サポート", "より豊富な文と例文", "完全な語彙管理"],
            buttonText: "ライセンスを購入",
        },
    },
    daily: {
        title: "デイリークイズ",
        intro: "短い日替わりの単語推測チャレンジです。",
        loading: "今日のチャレンジを読み込み中...",
        error: "現在、今日の単語を読み込めません。",
        empty: "まだ今日のチャレンジはありません。",
    },
    assessment: {
        eyebrow: "レベル診断",
        title: "実用語彙レベルを見積もる",
        intro: "この簡易診断は、日々の練習に合った開始レベルを見つけるためのものです。",
        questions: "問題数",
        quickChecks: "問のクイックチェック",
        currentLevel: "現在のレベル",
        signInToSave: "ログインして保存",
        question: "問題",
        answered: "{total}問中 {score}問正解しました。",
        answerAll: "すべて答えると推奨レベルが表示されます。",
        seeResult: "結果を見る",
        recommendedLevel: "推奨レベル",
        recommendedDescription: "まずはこのレベルを既定にして、後で必要なら調整してください。",
        applying: "適用中...",
        applyLevel: "このレベルを適用",
        signInToApply: "ログインして適用",
        goToDaily: "デイリーへ移動",
        saveSuccess: "レベルを {level} に更新しました。",
        saveError: "レベル更新に失敗しました。後でもう一度お試しください。",
    },
    reviewPage: {
        eyebrow: "進捗",
        loginTitle: "復習のリズムをひと目で確認",
        loginBody: "期限のキュー、最近の活動、記憶プロフィール、次の最適な行動をまとめて確認できます。",
        feature1Title: "期限キューの概要",
        feature1Body: "どれだけの単語が待っているかを確認し、次の復習ラウンドを始めるタイミングを判断できます。",
        feature2Title: "記憶プロフィール",
        feature2Body: "不安定な単語、安定した単語、支援が必要な領域を素早く見つけられます。",
        feature3Title: "週間モメンタム",
        feature3Body: "復習量、連続日数、新規追加を追い、進捗を見える化します。",
        loginCta: "ログインして進捗を見る",
        title: "学習ダッシュボード",
        intro: "期限が来ている内容を把握し、脆い記憶を見つけ、準備ができたらすぐ復習に入れます。",
        loadingBadge: "読み込み中...",
        wordsDue: "{count} 語が期限到来",
        startReview: "復習開始",
        openVocabulary: "語彙を開く",
        loading: "復習ダッシュボードを読み込み中...",
        statDueNow: "今すぐ",
        statDueNowHint: "復習キューで待っている単語",
        statLearning: "学習中",
        statLearningHint: "まだ記憶が安定していない単語",
        statInReview: "復習中",
        statInReviewHint: "間隔反復サイクルに入っている単語",
        statMastered: "習得済み",
        statMasteredHint: "長い間隔に進んでいる単語",
        statAddedThisWeek: "今週追加",
        statAddedThisWeekHint: "システムに入った新しい単語",
        statReviewsToday: "今日の復習",
        statReviewsTodayHint: "深夜以降 {count} 回スキップ",
        statCurrentLevel: "現在レベル",
        statCurrentLevelHint: "{count} 日連続学習",
        activityTitle: "7日間の活動",
        activityBody: "過去1週間の復習数と新規追加数。",
        reviewsBarTitle: "{count} 回復習",
        addedBarTitle: "{count} 件追加",
        memoryProfileTitle: "記憶プロフィール",
        memoryProfileBody: "記憶モデルを分かりやすい状態に変換して表示します。",
        fragile: "不安定",
        building: "構築中",
        stable: "安定",
        mastered: "習得済み",
        nextActionTitle: "次のおすすめ",
        nextActionReview: "期限の来た単語があります。先に片づけるのが最も効果的です。",
        nextActionRead: "新しい入力を増やすこともできますが、まずはキューの健康を優先しましょう。",
        nextActionWordbook: "キューは落ち着いています。ここで復習を続けるか、語彙で調整できます。",
        dueNowSummary: "今すぐ {count} 語が期限到来",
        streakSummary: "{count} 日連続アクティブ",
        addedThisWeekSummary: "今週 {count} 語追加",
        oftenWrongTitle: "よく間違える単語",
        oftenWrongBody: "繰り返し誤答していて難度も上がっている単語です。",
        wrongAnswers: "{count} 回誤答",
        difficulty: "難度 {count}",
        stability: "安定度 {count}",
        noOftenWrong: "まだ繰り返し間違える単語はありません。",
        needsHintsTitle: "ヒント依存",
        needsHintsBody: "支援があると解けるが、まだ内在化されていない単語です。",
        hintedCompletions: "{count} 回ヒント付き完了",
        noNeedsHints: "まだヒント依存の高い単語はありません。",
        mostSkippedTitle: "最もスキップされた単語",
        mostSkippedBody: "解く前に飛ばしがちな単語です。",
        skips: "{count} 回スキップ",
        noMostSkipped: "まだスキップの多い単語はありません。",
    },
    literatureTimeline: {
        unknownYear: "年代不明",
        allContent: "すべての文学",
        detailLoadFailed: "この抜粋を今は読み込めません。",
        listLoadFailed: "タイムラインを今は読み込めません。",
        viewAll: "すべて表示",
        loadingMore: "読み込み中...",
        loadingContent: "抜粋を読み込み中...",
    },
    practice: {
        loadingWords: "練習単語を読み込み中...",
        loadError: "現在、練習単語を読み込めません。",
        empty: "練習できる単語がありません。",
    },
    toolbox: {
        removeSavedWord: "保存済み単語から削除",
        saveWord: "単語を保存",
        saved: "保存済み",
        save: "保存",
        ignoreWord: "この単語を無視",
        ignore: "無視",
        more: "その他",
        shuffle: "シャッフル",
        keyboardHelp: "キーボードヘルプ",
        hideHelp: "ヘルプを隠す",
        report: "報告",
        closePractice: "練習を閉じる",
        keyboard: "キーボード",
        keyboardItems: [
            { keycap: "1", label: "ヒント" },
            { keycap: "2", label: "発音" },
            { keycap: "Enter", label: "表示 / 次へ" },
            { keycap: "<-", label: "前へ" },
            { keycap: "->", label: "次へ" },
        ],
    },
    reportDialog: {
        title: "報告ありがとうございます",
        placeholder: "この単語の精度を改善するための内容を教えてください。",
        submit: "送信",
        cancel: "キャンセル",
    },
    starRating: {
        familiarity: "親密度:",
        successHint: "よくできました。<Enter> で続行します。",
    },
    cardComposer: {
        createTitle: "カードを作成",
        editTitle: "カードを編集",
        intro: "テキスト、画像、音声、リンクからカードを組み立てます。学習者はまず表面を見て、あとで答えを表示します。",
        activeInReview: "復習で有効",
        titleRequired: "タイトルは必須です。",
        blocksRequired: "表面と答えにはそれぞれ少なくとも1つの入力済みブロックが必要です。",
        unableToSave: "カードを保存できませんでした。",
        titlePlaceholder: "カードタイトル",
        saving: "保存中...",
        cancel: "キャンセル",
    },
    cardBlocks: {
        imageAlt: "カード画像",
        optionalIntro: "オプションのブロックは答えの後に表示されます。",
        requiredIntro: "学習者に見せたい順にブロックを追加してください。",
        noBlocks: "まだブロックがありません。",
        remove: "削除",
        textPlaceholder: "表面、答え、メモをここに入力...",
        urlPlaceholder: "{type} URL",
        linkLabelPlaceholder: "リンクラベル",
        captionPlaceholder: "キャプション",
        types: {
            text: "テキスト",
            image: "画像",
            audio: "音声",
            link: "リンク",
        },
    },
    deckDetail: {
        loginTitle: "このデッキを管理するにはログインしてください",
        loginBody: "デッキの編集、複数ブロックのカード作成、復習での有効/無効の管理ができます。",
        loginCta: "ログインして続行",
        loading: "デッキを読み込み中...",
        unableToLoad: "このデッキを読み込めませんでした。",
        backToCards: "カードへ戻る",
        reviewThisDeck: "このデッキを復習",
        eyebrow: "デッキ",
        deckStats: "{cards} 枚 · 今すぐ {due} 枚 · 新規 {newCards} 枚",
        archiveDeck: "デッキをアーカイブ",
        unarchiveDeck: "アーカイブ解除",
        deleteDeck: "デッキを削除",
        deckNameRequired: "デッキ名は必須です。",
        unableToLoadDeck: "デッキを読み込めませんでした。",
        unableToSaveDeck: "デッキを保存できませんでした。",
        unableToUpdateArchive: "アーカイブ状態を更新できませんでした。",
        deleteDeckConfirm: "「{name}」とそのカードをすべて削除しますか？",
        unableToDeleteDeck: "デッキを削除できませんでした。",
        unableToCreateCard: "カードを作成できませんでした。",
        unableToUpdateCard: "カードを更新できませんでした。",
        deleteCardConfirm: "このカードを削除しますか？",
        unableToDeleteCard: "カードを削除できませんでした。",
        deckNamePlaceholder: "デッキ名",
        deckDescriptionPlaceholder: "このデッキは何を扱いますか？",
        savingDeck: "保存中...",
        saveDeck: "デッキを保存",
        createCard: "カードを作成",
        saveCard: "カードを保存",
        cardsInDeck: "このデッキのカード",
        cardsInDeckBody: "既存カードをその場で編集したり、デッキを削除せずに停止できます。",
        noCards: "まだカードがありません。上で最初のカードを作成してください。",
        statusNew: "新規",
        statusActive: "有効",
        statusPaused: "一時停止",
        edit: "編集",
        delete: "削除",
        prompt: "表面",
        answer: "答え",
        notes: "メモ",
    },
    customPractice: {
        emptyContent: "内容が空です。",
        placeholder: "練習したい単語リストを貼り付けてください...",
        attachFile: "ファイルを添付",
        practise: "練習",
    },
    videoDemo: {
        title: "Pro にはさらに多くの機能があります",
    },
    helpPanel: {
        title: "キーボードショートカット",
        closePanel: "パネルを閉じる",
        items: [
            { keycap: "1", label: "ヒント" },
            { keycap: "2", label: "発音" },
            { keycap: "3", label: "表示" },
            { keycap: "4", label: "次へ" },
        ],
    },
    wordSlideOver: {
        title: "単語リスト",
        closePanel: "パネルを閉じる",
    },
    activation: {
        title: "Pro を有効化",
        invalidLicense: "無効なライセンス: {reason}",
        license: "ライセンス",
        placeholder: "xxxxx-xxxxx-xxxxx-xxxxx",
        activate: "有効化",
        buyLicense: "ライセンスを購入",
    },
})

dictionaries.ko = mergeDictionary(dictionaries.en, {
    nav: {
        literature: "문학",
        vocabulary: "어휘",
        progress: "진행",
        pricing: "요금",
        tagline: "언어의 경계가 세계의 윤곽을 만든다.",
    },
    menu: {
        openToolsMenu: "도구 메뉴 열기",
        quickSearch: "빠른 검색",
        cardsPreview: "카드",
        previewTag: "Preview",
        savedLiterature: "저장한 문학",
        dailyGuess: "오늘의 퀴즈",
        imageMode: "이미지 모드",
        gradingExercise: "레벨 연습",
        chromeExtension: "Chrome 확장",
        about: "About",
        appearance: "테마",
        language: "언어",
        darkMode: "다크",
        lightMode: "라이트",
        english: "English",
        chinese: "中文",
        japanese: "日本語",
        korean: "한국어",
    },
    auth: {
        loading: "로딩 중...",
        signIn: "로그인",
        level: "레벨",
        assessYourLevel: "레벨 진단",
        signOut: "로그아웃",
        expireAt: "만료일",
    },
    search: {
        open: "빠른 검색 열기",
        title: "빠른 단어 검색",
        description: "페이지를 벗어나지 않고 단어를 검색하세요.",
        shortcutHint: "단축키: / 또는 Ctrl/Cmd + K",
        placeholder: "단어 입력",
        submit: "검색",
        searching: "검색 중...",
        empty: "단어를 검색하면 뜻이 표시됩니다.",
        notFound: "해당 단어를 찾지 못했습니다.",
        examples: "예문",
        phonetic: "발음",
        definition: "정의",
        close: "닫기",
        chinese: "중국어",
    },
    common: {
        backHome: "홈으로",
        backToLiterature: "문학으로 돌아가기",
        archived: "보관됨",
        noDescription: "설명이 아직 없습니다.",
        cancel: "취소",
    },
    savedLiterature: {
        title: "저장한 문학",
        intro: "홈페이지에서 저장한 문학 발췌문을 모아보는 서가입니다.",
        loginTitle: "저장한 문학을 보려면 로그인하세요",
        loginBody: "저장한 발췌문은 계정과 연결되어 있으므로 먼저 로그인해야 합니다.",
        loginCta: "로그인하고 계속",
        loading: "저장한 발췌문 불러오는 중...",
        emptyTitle: "아직 저장한 발췌문이 없습니다",
        emptyBody: "홈에서 문학 발췌문을 저장하면 여기에 표시됩니다.",
        savedCount: "{count}개 저장됨",
        openLiterature: "문학 둘러보기",
    },
    cards: {
        title: "카드",
        marketingTitle: "실제로 만난 단어로 덱을 만드세요.",
        marketingBody: "읽기와 검색을 반복 가능한 복습 시스템으로 바꿉니다. 덱을 만들고 어려운 단어를 모으고, 자신의 자료에 맞춘 간격 반복을 유지하세요.",
        feature1Title: "집중형 덱 만들기",
        feature1Body: "시험 어휘, 문학, 주제별 카드를 분리해 관리할 수 있습니다.",
        feature2Title: "도래한 항목 먼저 복습",
        feature2Body: "지금 주의가 필요한 것을 보고 짧고 꾸준한 복습을 유지하세요.",
        feature3Title: "문맥 유지",
        feature3Body: "카드는 읽은 문장과 글에서 올 때 가장 효과적입니다.",
        loginCta: "로그인하고 카드 열기",
        decksTitle: "덱 작업 공간",
        decksBody: "작고 집중된 덱을 만들고, 도래량을 확인하고, 준비되면 바로 복습할 수 있습니다.",
        statsDecks: "덱",
        statsCards: "카드",
        statsDueNow: "지금 도래",
        openReview: "복습 열기",
        createDeckTitle: "새 덱 만들기",
        createDeckBody: "짧고 구체적인 이름을 쓰면 오래 쓰기 좋습니다.",
        deckName: "덱 이름",
        deckDescription: "설명",
        createDeck: "덱 만들기",
        creatingDeck: "생성 중...",
        createDeckFailed: "덱 생성에 실패했습니다.",
        libraryTitle: "덱 라이브러리",
        libraryBody: "덱을 열어 카드 추가, 도래 확인, 내용 검토를 할 수 있습니다.",
        loadingDecks: "덱 불러오는 중...",
        emptyDecks: "아직 덱이 없습니다. 위에서 첫 덱을 만들어보세요.",
        loadDecksFailed: "덱을 불러오지 못했습니다.",
        cardsCount: "{count}장",
        dueCount: "{count}장 도래",
        newCount: "{count}장 신규",
    },
    cardsReview: {
        title: "카드 복습",
        loginCta: "로그인하고 카드 복습",
        backToCards: "카드로 돌아가기",
        queueTitle: "커스텀 덱 메모리 큐",
        queueBody: "지금 복습할 카드를 확인하고, 부담을 본 다음 자기 평가 복습을 시작하세요.",
        allDecks: "모든 덱",
        startReview: "복습 시작",
        loadingCenter: "카드 복습 센터 불러오는 중...",
        decksWithDueCards: "도래한 카드가 있는 덱",
        noDueCards: "지금은 도래한 카드가 없습니다.",
        currentRoundPreview: "현재 라운드",
        filteredToOneDeck: "이 큐는 하나의 덱으로 필터링되어 있습니다.",
        blendedQueue: "이 큐는 현재 도래한 덱을 함께 보여줍니다.",
        cardsLabel: "카드",
        noCardsInFilter: "이 필터에는 도래한 카드가 없습니다.",
        nothingReady: "아직 복습할 준비가 된 카드가 없습니다.",
        continue: "계속",
        noCardsLeft: "이 라운드에 남은 카드가 없습니다.",
        backToCenter: "복습 센터로 돌아가기",
        closeRound: "라운드 닫기",
        prompt: "앞면",
        answer: "정답",
        revealHelp: "평가할 준비가 되면 정답을 펼치세요.",
        notes: "노트",
        revealAnswer: "정답 보기",
        again: "다시",
        hard: "어려움",
        good: "좋음",
        easy: "쉬움",
        unableToLoad: "카드 복습을 불러오지 못했습니다.",
        unableToSave: "복습 결과를 저장하지 못했습니다.",
        cardProgress: "{current}/{total}장 · {badge}",
        badges: {
            new: "신규",
            learning: "학습 중",
            review: "복습 중",
            mastered: "숙달",
            fragile: "불안정",
            building: "형성 중",
            stable: "안정",
        },
    },
    vocabulary: {
        title: "어휘 라이브러리",
        description: "저장한 단어를 보고, 기억 상태로 필터링하고, 언제든 연습으로 바꿀 수 있습니다.",
        feature1Title: "유용한 단어 저장",
        feature1Body: "읽기, 연습, 검색에서 만난 단어를 한 곳에 모으세요.",
        feature2Title: "기억 상태별 필터",
        feature2Body: "불안정한 단어와 안정적인 단어를 나눠 복습 시간을 중요한 곳에 쓰세요.",
        feature3Title: "내 단어로 연습",
        feature3Body: "이미 모은 어휘에서 직접 훈련할 수 있습니다.",
        loginCta: "로그인하고 어휘 열기",
        library: "어휘",
        memoryFilter: "필터: {label}",
        searchPlaceholder: "저장한 단어 검색",
        importWords: "단어 가져오기",
        practise: "연습",
        practiseSavedWords: "저장한 단어 연습",
        openCustomPractise: "사용자 연습 열기",
    },
    listMenu: {
        allWords: "모든 단어",
        unfamiliar: "낯선 단어",
        familiarity1: "친숙도 1",
        familiarity2: "친숙도 2",
        familiarity3: "친숙도 3",
        familiarity4: "친숙도 4",
        familiarity5: "친숙도 5",
        ignored: "무시됨",
    },
    inputModal: {
        title: "단어 가져오기",
        placeholder: "단어를 붙여넣으세요. 공백, 쉼표, 줄바꿈으로 구분할 수 있습니다.",
        confirm: "가져오기",
        cancel: "취소",
    },
    wordBook: {
        word: "단어",
        memory: "기억 상태",
        familiarity: "친숙도",
        query: "조회 수",
        actions: "동작",
        definition: "정의",
        loadingDefinition: "정의 불러오는 중...",
        fragile: "불안정",
        building: "형성 중",
        stable: "안정",
        mastered: "숙달",
        untracked: "추적 안 됨",
        ignoreWord: "단어 무시",
        listenOnYouGlish: "YouGlish에서 듣기",
        removeWord: "단어 삭제",
        empty: "아직 저장된 단어가 없습니다.",
    },
    pagination: {
        previous: "이전",
        next: "다음",
        range: "{start}부터 {end}까지 / 총 {total}",
    },
    home: {
        noPracticeWordsLeft: "남은 연습 단어가 없습니다",
        noPracticeWordsDescription: "이 글의 단어는 이미 익숙해서 지금은 추가 연습이 필요하지 않습니다.",
    },
    reading: {
        author: "저자",
        startPractice: "연습 시작",
        preparingPractice: "연습 준비 중",
        savePassage: "이 글 저장",
        removeSavedPassage: "저장 해제",
        previewSaveUnavailable: "미리보기 글은 저장할 수 없습니다",
        loginToSavePassages: "글을 저장하려면 로그인하세요",
        lookup: "뜻",
        canonical: "원형",
        addToWordList: "어휘에 추가",
        addedToWordList: "어휘에 추가됨",
        loginToAddWords: "단어를 추가하려면 로그인하세요",
        loadingDefinition: "정의 불러오는 중...",
        noDefinition: "아직 정의가 없습니다.",
        loginToViewDefinitions: "정의를 보려면 로그인하세요.",
        failedToLoadDefinition: "정의를 불러오지 못했습니다.",
    },
    pricing: {
        eyebrow: "플랜",
        title: "전체 학습 워크플로우를 해제하세요.",
        intro: "무료로 먼저 사용해 보고, 필요하면 더 깊은 콘텐츠와 고급 모드로 업그레이드하세요.",
        unlockTitle: "Pro에서 열리는 것",
        unlockDescription: "HowToSay Pro는 더 구조적인 흐름과 장기 유지 관리를 원하는 학습자를 위한 플랜입니다.",
        advancedTitle: "고급 연습 모드",
        advancedDescription: "더 풍부한 연습 형식과 음성 지원, 더 강한 회상 훈련을 제공합니다.",
        coverageTitle: "더 깊은 콘텐츠",
        coverageDescription: "더 넓은 어휘와 예문, 더 강한 문맥 지원을 제공합니다.",
        controlTitle: "개인 학습 제어",
        controlDescription: "자신만의 단어장을 유지하고 중요한 것을 정리하며 계속 복습할 수 있습니다.",
        requestProTitle: "Pro 신청",
        requestProContent: "학습 용도와 예상 사용량을 bytegush@hotmail.com 으로 보내주세요.",
        requestProConfirm: "돌아가기",
    },
    pricingTiers: {
        free: {
            title: "무료",
            price: "무료",
            description: "가벼운 일상 연습과 평가용.",
            features: ["일일 사용 제한", "핵심 학습 모드", "Pro 접근 요청"],
            buttonText: "Pro 신청",
        },
        pro: {
            title: "Pro",
            price: "$4/년",
            description: "제품을 본격적으로 쓰고 싶은 학습자용.",
            features: ["모든 학습 모드 해제", "고급 어휘 및 음성 지원", "더 풍부한 문장과 예문", "완전한 단어장 관리"],
            buttonText: "라이선스 구매",
        },
        edu: {
            title: "Edu Pro",
            price: "$2/년",
            description: "교육용 이메일 인증 학생용.",
            features: ["모든 학습 모드 해제", "고급 어휘 및 음성 지원", "더 풍부한 문장과 예문", "완전한 단어장 관리"],
            buttonText: "라이선스 구매",
        },
    },
    daily: {
        title: "오늘의 퀴즈",
        intro: "짧은 일일 단어 추측 챌린지입니다.",
        loading: "오늘의 챌린지 불러오는 중...",
        error: "현재 오늘의 단어를 불러올 수 없습니다.",
        empty: "아직 오늘의 챌린지가 없습니다.",
    },
    assessment: {
        eyebrow: "레벨 평가",
        title: "실용 어휘 레벨 추정",
        intro: "이 간단한 평가는 일상 연습에 적합한 시작 레벨을 고르는 데 도움을 줍니다.",
        questions: "문항 수",
        quickChecks: "개의 빠른 체크",
        currentLevel: "현재 레벨",
        signInToSave: "로그인 후 저장",
        question: "문항",
        answered: "{total}문항 중 {score}문항 정답입니다.",
        answerAll: "모든 문항에 답하면 추천 레벨을 볼 수 있습니다.",
        seeResult: "결과 보기",
        recommendedLevel: "추천 레벨",
        recommendedDescription: "우선 이 레벨을 기본값으로 쓰고, 필요하면 나중에 조정하세요.",
        applying: "적용 중...",
        applyLevel: "이 레벨 적용",
        signInToApply: "로그인 후 적용",
        goToDaily: "오늘의 퀴즈로 이동",
        saveSuccess: "레벨이 {level}(으)로 업데이트되었습니다.",
        saveError: "레벨 업데이트에 실패했습니다. 다시 시도해주세요.",
    },
    reviewPage: {
        eyebrow: "진행",
        loginTitle: "복습 리듬을 한눈에 확인",
        loginBody: "도래 큐, 최근 활동, 기억 프로필, 다음 최적 행동을 한곳에서 볼 수 있습니다.",
        feature1Title: "도래 큐 개요",
        feature1Body: "얼마나 많은 단어가 기다리는지 보고 다음 복습을 시작할 타이밍을 판단하세요.",
        feature2Title: "기억 프로필",
        feature2Body: "불안정한 단어와 안정된 단어, 더 지원이 필요한 영역을 빠르게 찾을 수 있습니다.",
        feature3Title: "주간 모멘텀",
        feature3Body: "복습량, 연속일, 새 단어 추가를 추적하며 진행을 눈에 보이게 합니다.",
        loginCta: "로그인하고 진행 보기",
        title: "학습 대시보드",
        intro: "무엇이 도래했는지 보고, 기억이 약한 부분을 찾고, 준비되면 곧바로 복습을 시작하세요.",
        loadingBadge: "로딩 중...",
        wordsDue: "{count}개 단어 도래",
        startReview: "복습 시작",
        openVocabulary: "어휘 열기",
        loading: "복습 대시보드 불러오는 중...",
        statDueNow: "지금 도래",
        statDueNowHint: "복습 큐에서 기다리는 단어",
        statLearning: "학습 중",
        statLearningHint: "아직 기억이 안정되지 않은 단어",
        statInReview: "복습 중",
        statInReviewHint: "간격 반복 사이클에 들어간 단어",
        statMastered: "숙달",
        statMasteredHint: "더 긴 간격으로 밀린 단어",
        statAddedThisWeek: "이번 주 추가",
        statAddedThisWeekHint: "시스템에 들어온 새 단어",
        statReviewsToday: "오늘 복습",
        statReviewsTodayHint: "자정 이후 {count}회 건너뜀",
        statCurrentLevel: "현재 레벨",
        statCurrentLevelHint: "{count}일 연속 학습",
        activityTitle: "최근 7일 활동",
        activityBody: "지난 일주일 동안의 복습과 신규 추가량.",
        reviewsBarTitle: "{count}회 복습",
        addedBarTitle: "{count}개 추가",
        memoryProfileTitle: "기억 프로필",
        memoryProfileBody: "기억 모델을 이해하기 쉬운 상태로 바꿔 보여줍니다.",
        fragile: "불안정",
        building: "형성 중",
        stable: "안정",
        mastered: "숙달",
        nextActionTitle: "다음 추천 행동",
        nextActionReview: "이미 도래한 단어가 있습니다. 먼저 처리하는 것이 가장 빠른 개선 방법입니다.",
        nextActionRead: "새 입력을 더할 수도 있지만, 우선 큐를 건강하게 유지하는 편이 좋습니다.",
        nextActionWordbook: "큐가 안정적입니다. 여기서 복습을 계속하거나 어휘에서 다듬을 수 있습니다.",
        dueNowSummary: "지금 {count}개 단어 도래",
        streakSummary: "{count}일 연속 활동",
        addedThisWeekSummary: "이번 주 {count}개 단어 추가",
        oftenWrongTitle: "자주 틀리는 단어",
        oftenWrongBody: "반복해서 오답이 나오고 난이도도 올라가는 단어입니다.",
        wrongAnswers: "{count}회 오답",
        difficulty: "난이도 {count}",
        stability: "안정도 {count}",
        noOftenWrong: "아직 반복 오답이 많은 단어는 없습니다.",
        needsHintsTitle: "힌트 의존",
        needsHintsBody: "도움이 있으면 맞히지만 아직 충분히 내재화되지 않은 단어입니다.",
        hintedCompletions: "{count}회 힌트로 완료",
        noNeedsHints: "아직 힌트 의존도가 높은 단어는 없습니다.",
        mostSkippedTitle: "가장 많이 건너뜀",
        mostSkippedBody: "풀기 전에 지나치기 쉬운 단어입니다.",
        skips: "{count}회 건너뜀",
        noMostSkipped: "아직 많이 건너뛴 단어는 없습니다.",
    },
    literatureTimeline: {
        unknownYear: "연도 미상",
        allContent: "전체 문학",
        detailLoadFailed: "지금은 이 발췌문을 불러올 수 없습니다.",
        listLoadFailed: "지금은 타임라인을 불러올 수 없습니다.",
        viewAll: "전체 보기",
        loadingMore: "불러오는 중...",
        loadingContent: "발췌문 불러오는 중...",
    },
    practice: {
        loadingWords: "연습 단어 불러오는 중...",
        loadError: "지금은 연습 단어를 불러올 수 없습니다.",
        empty: "연습할 단어가 없습니다.",
    },
    toolbox: {
        removeSavedWord: "저장한 단어에서 제거",
        saveWord: "단어 저장",
        saved: "저장됨",
        save: "저장",
        ignoreWord: "이 단어 무시",
        ignore: "무시",
        more: "더보기",
        shuffle: "섞기",
        keyboardHelp: "키보드 도움말",
        hideHelp: "도움말 숨기기",
        report: "신고",
        closePractice: "연습 닫기",
        keyboard: "키보드",
        keyboardItems: [
            { keycap: "1", label: "힌트" },
            { keycap: "2", label: "발음" },
            { keycap: "Enter", label: "보기 / 다음" },
            { keycap: "<-", label: "이전" },
            { keycap: "->", label: "다음" },
        ],
    },
    reportDialog: {
        title: "제보 감사합니다",
        placeholder: "이 단어의 정확도를 높이기 위해 어떤 문제가 있었는지 알려주세요.",
        submit: "제출",
        cancel: "취소",
    },
    starRating: {
        familiarity: "친숙도:",
        successHint: "잘했어요. <Enter>를 눌러 계속하세요.",
    },
    cardComposer: {
        createTitle: "카드 만들기",
        editTitle: "카드 수정",
        intro: "텍스트, 이미지, 오디오, 링크로 카드를 구성하세요. 학습자는 먼저 앞면을 보고 나중에 정답을 펼칩니다.",
        activeInReview: "복습에 활성화",
        titleRequired: "제목은 필수입니다.",
        blocksRequired: "앞면과 정답은 각각 최소 한 개의 입력된 블록이 필요합니다.",
        unableToSave: "카드를 저장하지 못했습니다.",
        titlePlaceholder: "카드 제목",
        saving: "저장 중...",
        cancel: "취소",
    },
    cardBlocks: {
        imageAlt: "카드 이미지",
        optionalIntro: "선택 블록은 정답 뒤에 표시됩니다.",
        requiredIntro: "학습자가 볼 순서대로 블록을 추가하세요.",
        noBlocks: "아직 블록이 없습니다.",
        remove: "삭제",
        textPlaceholder: "앞면, 정답 또는 메모를 여기에 입력하세요...",
        urlPlaceholder: "{type} URL",
        linkLabelPlaceholder: "링크 라벨",
        captionPlaceholder: "캡션",
        types: {
            text: "텍스트",
            image: "이미지",
            audio: "오디오",
            link: "링크",
        },
    },
    deckDetail: {
        loginTitle: "이 덱을 관리하려면 로그인하세요",
        loginBody: "덱 자체를 수정하고, 여러 블록 카드 만들고, 복습 활성 상태를 관리할 수 있습니다.",
        loginCta: "로그인하고 계속",
        loading: "덱 불러오는 중...",
        unableToLoad: "이 덱을 불러오지 못했습니다.",
        backToCards: "카드로 돌아가기",
        reviewThisDeck: "이 덱 복습",
        eyebrow: "덱",
        deckStats: "{cards}장 · 지금 {due}장 도래 · 신규 {newCards}장",
        archiveDeck: "덱 보관",
        unarchiveDeck: "보관 해제",
        deleteDeck: "덱 삭제",
        deckNameRequired: "덱 이름은 필수입니다.",
        unableToLoadDeck: "덱을 불러오지 못했습니다.",
        unableToSaveDeck: "덱을 저장하지 못했습니다.",
        unableToUpdateArchive: "보관 상태를 업데이트하지 못했습니다.",
        deleteDeckConfirm: "\"{name}\" 덱과 모든 카드를 삭제하시겠습니까?",
        unableToDeleteDeck: "덱을 삭제하지 못했습니다.",
        unableToCreateCard: "카드를 만들지 못했습니다.",
        unableToUpdateCard: "카드를 수정하지 못했습니다.",
        deleteCardConfirm: "이 카드를 삭제하시겠습니까?",
        unableToDeleteCard: "카드를 삭제하지 못했습니다.",
        deckNamePlaceholder: "덱 이름",
        deckDescriptionPlaceholder: "이 덱은 어떤 내용을 다루나요?",
        savingDeck: "저장 중...",
        saveDeck: "덱 저장",
        createCard: "카드 만들기",
        saveCard: "카드 저장",
        cardsInDeck: "이 덱의 카드",
        cardsInDeckBody: "기존 카드를 바로 편집하거나 덱을 삭제하지 않고 비활성화할 수 있습니다.",
        noCards: "아직 카드가 없습니다. 위에서 첫 카드를 만들어보세요.",
        statusNew: "신규",
        statusActive: "활성",
        statusPaused: "일시중지",
        edit: "수정",
        delete: "삭제",
        prompt: "앞면",
        answer: "정답",
        notes: "노트",
    },
    customPractice: {
        emptyContent: "내용이 비어 있습니다.",
        placeholder: "연습할 단어 목록을 붙여넣으세요...",
        attachFile: "파일 첨부",
        practise: "연습",
    },
    videoDemo: {
        title: "Pro에는 더 많은 기능이 있습니다",
    },
    helpPanel: {
        title: "키보드 단축키",
        closePanel: "패널 닫기",
        items: [
            { keycap: "1", label: "힌트" },
            { keycap: "2", label: "발음" },
            { keycap: "3", label: "보기" },
            { keycap: "4", label: "다음" },
        ],
    },
    wordSlideOver: {
        title: "단어 목록",
        closePanel: "패널 닫기",
    },
    activation: {
        title: "Pro 활성화",
        invalidLicense: "유효하지 않은 라이선스: {reason}",
        license: "라이선스",
        placeholder: "xxxxx-xxxxx-xxxxx-xxxxx",
        activate: "활성화",
        buyLicense: "라이선스 구매",
    },
})

export function formatCopy(template: string, values: Record<string, string | number>) {
    return template.replace(/\{(\w+)\}/g, (_, key: string) => String(values[key] ?? ""))
}
