export type Locale = "en" | "zh"
export type Theme = "dark" | "light"
export type Dictionary = Record<string, any>

export const dictionaries: Record<Locale, Dictionary> = {
    en: {
        nav: {
            literature: "LITERATURE",
            vocabulary: "VOCABULARY",
            progress: "PROGRESS",
            cards: "CARDS",
            pricing: "PRICING",
            title: "How To Say",
            tagline: "The limits of my language mean the limits of my world.",
        },
        menu: {
            openToolsMenu: "Open tools menu",
            dailyGuess: "Daily Guess",
            imageMode: "Image Mode",
            gradingExercise: "Grading Exercise",
            chromeExtension: "Chrome Extension",
            about: "About",
            appearance: "Appearance",
            language: "Language",
            darkMode: "Dark",
            lightMode: "Light",
            english: "English",
            chinese: "中文",
        },
        auth: {
            loading: "Loading...",
            signIn: "Sign In",
            level: "Level",
            assessYourLevel: "Assess your level",
            signOut: "Sign Out",
            expireAt: "Expire at",
        },
        common: {
            backHome: "Back Home",
            archived: "Archived",
            noDescription: "No description yet.",
        },
        cards: {
            title: "Cards",
            marketingTitle: "Build decks from the words you actually meet.",
            marketingBody: "Turn reading and lookup into a reusable review system. Create decks, collect hard words, and keep spaced review tied to your own material.",
            feature1Title: "Create focused decks",
            feature1Body: "Separate exam vocabulary, literature, or topic-based cards instead of mixing everything together.",
            feature2Title: "Review what is due",
            feature2Body: "See what needs attention now and keep your review sessions short and consistent.",
            feature3Title: "Stay close to context",
            feature3Body: "Cards work best when they come from sentences and passages you have already seen.",
            loginCta: "Sign in to open cards",
            decksTitle: "Your deck workspace",
            decksBody: "Create small focused decks, keep an eye on due volume, and jump into review when you are ready.",
            statsDecks: "Decks",
            statsCards: "Cards",
            statsDueNow: "Due now",
            openReview: "Open review",
            createDeckTitle: "Create a new deck",
            createDeckBody: "Use short, specific names so each deck stays useful over time.",
            deckName: "Deck name",
            deckDescription: "Description",
            createDeck: "Create deck",
            creatingDeck: "Creating...",
            createDeckFailed: "Failed to create deck.",
            libraryTitle: "Deck library",
            libraryBody: "Open a deck to add cards, inspect due counts, and review its contents.",
            loadingDecks: "Loading decks...",
            emptyDecks: "No decks yet. Create your first one above.",
            loadDecksFailed: "Failed to load decks.",
            cardsCount: "{count} cards",
            dueCount: "{count} due",
            newCount: "{count} new",
        },
        vocabulary: {
            title: "Your vocabulary library",
            description: "Browse saved words, filter by familiarity, and turn your collection into active practice whenever you want.",
            feature1Title: "Save useful words",
            feature1Body: "Keep words that came from reading, practice, and lookup in one place.",
            feature2Title: "Filter by memory state",
            feature2Body: "Separate fragile words from stable ones so review time goes where it matters.",
            feature3Title: "Practice from your own list",
            feature3Body: "Start training directly from the vocabulary you have already collected.",
            loginCta: "Sign in to open vocabulary",
            library: "Vocabulary",
            memoryFilter: "Filter: {label}",
            searchPlaceholder: "Search your words",
            importWords: "Import words",
            practise: "Practice",
            practiseSavedWords: "Practice saved words",
            openCustomPractise: "Open custom practice",
        },
        listMenu: {
            allWords: "All words",
            unfamiliar: "Unfamiliar",
            familiarity1: "Familiarity 1",
            familiarity2: "Familiarity 2",
            familiarity3: "Familiarity 3",
            familiarity4: "Familiarity 4",
            familiarity5: "Familiarity 5",
            ignored: "Ignored",
        },
        inputModal: {
            title: "Import words",
            placeholder: "Paste words here, separated by spaces, commas, or new lines.",
            confirm: "Import",
            cancel: "Cancel",
        },
        wordBook: {
            word: "Word",
            memory: "Memory",
            familiarity: "Familiarity",
            query: "Queries",
            actions: "Actions",
            definition: "Definition",
            loadingDefinition: "Loading definition...",
            fragile: "Fragile",
            building: "Building",
            stable: "Stable",
            mastered: "Mastered",
            untracked: "Untracked",
            ignoreWord: "Ignore word",
            listenOnYouGlish: "Listen on YouGlish",
            removeWord: "Remove word",
            empty: "No saved words yet.",
        },
        pagination: {
            previous: "Previous",
            next: "Next",
            range: "Showing {start} to {end} of {total} results",
        },
        home: {
            noPracticeWordsLeft: "No practice words left",
            noPracticeWordsDescription: "All words in this passage are already marked as familiar, so there is nothing left to practise here.",
        },
        reading: {
            author: "Author",
            startPractice: "Start practice",
            preparingPractice: "Preparing practice",
            savePassage: "Save this passage",
            removeSavedPassage: "Remove saved passage",
            previewSaveUnavailable: "Save is unavailable for preview passages",
            loginToSavePassages: "Login to save passages",
            lookup: "Lookup",
            canonical: "Canonical",
            addToWordList: "Add to word list",
            addedToWordList: "Added to word list",
            loginToAddWords: "Login to add words",
            loadingDefinition: "Loading definition...",
            noDefinition: "No definition available yet.",
            loginToViewDefinitions: "Login to view definitions.",
            failedToLoadDefinition: "Failed to load definition.",
        },
        about: {
            title: "About How To Say",
            intro: "How To Say is built for immersive vocabulary learning. It turns reading, guessing, bookmarking, and repeated exposure into one continuous workflow, so new words stay connected to real language instead of isolated lists.",
            readTitle: "Read in context",
            readDescription: "Learn through literary passages, examples, and sentence-level exposure instead of flashcards alone.",
            practiceTitle: "Practice actively",
            practiceDescription: "Move from recognition to recall with guessing flows, graded practice, and image-based prompts.",
            bankTitle: "Build your own bank",
            bankDescription: "Save words as you read, revisit them later, and keep your practice focused on what is still unfamiliar.",
            feedbackTitle: "Send feedback",
            feedbackDescription: "Share bugs, product suggestions, missing features, or anything that feels unclear.",
            feedbackPlaceholder: "Tell us what would make How To Say better...",
            feedbackThanks: "Thanks. Your feedback has been sent.",
            feedbackError: "Submission failed. Please try again.",
            feedbackSending: "Sending...",
            feedbackSubmit: "Submit feedback",
        },
        pricing: {
            eyebrow: "Plans",
            title: "Access the complete learning workflow.",
            intro: "Start free to evaluate the product, or upgrade for full access to advanced modes, deeper vocabulary coverage, and personal learning tools.",
            unlockTitle: "What Pro unlocks",
            unlockDescription: "HowToSay Pro is designed for learners who want a more structured workflow, deeper exposure, and better control over long-term vocabulary retention.",
            advancedTitle: "Advanced practice modes",
            advancedDescription: "Move beyond basic guessing with richer exercises, audio-supported prompts, and more demanding recognition-to-recall flows.",
            coverageTitle: "Deeper content coverage",
            coverageDescription: "Access broader vocabulary, more examples, and stronger sentence context for learning words in real usage rather than in isolation.",
            controlTitle: "Personal learning control",
            controlDescription: "Maintain your own word book, organize what matters, and keep reviewing with a workflow built for continuous progress.",
            requestProTitle: "Request Pro",
            requestProContent: "Please email bytegush@hotmail.com with your learning use case and expected usage.",
            requestProConfirm: "Go Back",
        },
        pricingTiers: {
            free: {
                title: "Free",
                price: "Free",
                description: "For evaluation and light daily practice.",
                features: ["Daily usage limits", "Core learning modes", "Request Pro access"],
                buttonText: "Request Pro",
            },
            pro: {
                title: "Pro",
                price: "$4/year",
                description: "For committed learners who want the full product.",
                features: [
                    "All learning modes unlocked",
                    "Advanced vocabulary and audio support",
                    "Richer sentence and example coverage",
                    "Full word book management",
                ],
                buttonText: "Buy License",
            },
            edu: {
                title: "Edu Pro",
                price: "$2/year",
                description: "For students with verified educational email access.",
                features: [
                    "All learning modes unlocked",
                    "Advanced vocabulary and audio support",
                    "Richer sentence and example coverage",
                    "Full word book management",
                ],
                buttonText: "Buy License",
            },
        },
        daily: {
            title: "Daily Guess",
            intro: "A short daily word-guess challenge with text clues and spelling practice.",
            loading: "Loading daily challenge...",
            error: "Unable to load today's words right now.",
            empty: "No daily challenge is available yet.",
        },
        assessment: {
            eyebrow: "Level Assessment",
            title: "Estimate your working vocabulary level",
            intro: "This quick assessment is meant to help you choose a useful starting level for daily practice. It is not a formal test, but it is good enough to calibrate your word flow before you begin.",
            questions: "Questions",
            quickChecks: "quick checks",
            currentLevel: "Current level",
            signInToSave: "Sign in to save",
            question: "Question",
            answered: "You answered {score} out of {total} correctly.",
            answerAll: "Answer all questions to see your suggested level.",
            seeResult: "See result",
            recommendedLevel: "Recommended level",
            recommendedDescription: "Use this as your default practice band. You can still fine-tune it later from your user menu if the words feel too easy or too dense.",
            applying: "Applying...",
            applyLevel: "Apply this level",
            signInToApply: "Sign in to apply",
            goToDaily: "Go to Daily Guess",
            saveSuccess: "Your level has been updated to {level}.",
            saveError: "Failed to update your level. Please try again.",
        },
    },
    zh: {
        nav: {
            literature: "文学",
            vocabulary: "词汇",
            progress: "进度",
            cards: "卡片",
            pricing: "定价",
            title: "How To Say",
            tagline: "语言的边界，就是世界的边界。",
        },
        menu: {
            openToolsMenu: "打开菜单",
            dailyGuess: "每日猜词",
            imageMode: "看图模式",
            gradingExercise: "分级练习",
            chromeExtension: "Chrome 扩展",
            about: "关于",
            appearance: "外观",
            language: "语言",
            darkMode: "夜间",
            lightMode: "白天",
            english: "English",
            chinese: "中文",
        },
        auth: {
            loading: "加载中...",
            signIn: "登录",
            level: "等级",
            assessYourLevel: "测试你的等级",
            signOut: "退出登录",
            expireAt: "到期时间",
        },
        common: {
            backHome: "返回首页",
            archived: "已归档",
            noDescription: "暂时还没有描述。",
        },
        cards: {
            title: "卡片",
            marketingTitle: "把真正遇到的词做成可复习的卡片组。",
            marketingBody: "把阅读和查词沉淀成可重复使用的复习系统。创建卡组、收集难词，让间隔复习始终贴着你的真实材料。",
            feature1Title: "建立聚焦卡组",
            feature1Body: "按考试、文学或主题拆分卡组，而不是把所有内容混在一起。",
            feature2Title: "优先复习到期内容",
            feature2Body: "随时看到现在最该复习的部分，让单次复习更短、更稳定。",
            feature3Title: "保持语境联系",
            feature3Body: "卡片最好来自你已经读过的句子和文章，而不是孤立条目。",
            loginCta: "登录后使用卡片",
            decksTitle: "你的卡组工作台",
            decksBody: "创建小而清晰的卡组，关注到期量，在合适的时候直接进入复习。",
            statsDecks: "卡组数",
            statsCards: "卡片数",
            statsDueNow: "当前到期",
            openReview: "开始复习",
            createDeckTitle: "创建新卡组",
            createDeckBody: "尽量用简短明确的名字，让卡组长期保持可用。",
            deckName: "卡组名称",
            deckDescription: "卡组描述",
            createDeck: "创建卡组",
            creatingDeck: "创建中...",
            createDeckFailed: "创建卡组失败。",
            libraryTitle: "卡组列表",
            libraryBody: "打开卡组后可以添加卡片、查看到期量并检查内容。",
            loadingDecks: "正在加载卡组...",
            emptyDecks: "还没有卡组，先在上面创建一个。",
            loadDecksFailed: "加载卡组失败。",
            cardsCount: "{count} 张卡片",
            dueCount: "{count} 张到期",
            newCount: "{count} 张新卡",
        },
        vocabulary: {
            title: "你的词汇库",
            description: "查看已保存单词，按熟悉度过滤，并随时把这些词转成主动练习。",
            feature1Title: "保存真正有用的词",
            feature1Body: "把阅读、练习和查词过程中遇到的单词集中到一个地方。",
            feature2Title: "按记忆状态过滤",
            feature2Body: "把脆弱词和稳定词分开，让复习时间用在真正需要的地方。",
            feature3Title: "从自己的词表练习",
            feature3Body: "直接从你已经收集的词汇开始训练，而不是重新找材料。",
            loginCta: "登录后打开词汇库",
            library: "词汇库",
            memoryFilter: "筛选：{label}",
            searchPlaceholder: "搜索已保存单词",
            importWords: "导入单词",
            practise: "练习",
            practiseSavedWords: "练习已保存单词",
            openCustomPractise: "打开自定义练习",
        },
        listMenu: {
            allWords: "全部单词",
            unfamiliar: "不熟悉",
            familiarity1: "熟悉度 1",
            familiarity2: "熟悉度 2",
            familiarity3: "熟悉度 3",
            familiarity4: "熟悉度 4",
            familiarity5: "熟悉度 5",
            ignored: "已忽略",
        },
        inputModal: {
            title: "导入单词",
            placeholder: "把单词粘贴到这里，支持空格、逗号或换行分隔。",
            confirm: "导入",
            cancel: "取消",
        },
        wordBook: {
            word: "单词",
            memory: "记忆状态",
            familiarity: "熟悉度",
            query: "查询次数",
            actions: "操作",
            definition: "释义",
            loadingDefinition: "正在加载释义...",
            fragile: "脆弱",
            building: "建立中",
            stable: "稳定",
            mastered: "掌握",
            untracked: "未跟踪",
            ignoreWord: "忽略单词",
            listenOnYouGlish: "在 YouGlish 收听",
            removeWord: "删除单词",
            empty: "还没有保存任何单词。",
        },
        pagination: {
            previous: "上一页",
            next: "下一页",
            range: "显示第 {start} 到 {end} 条，共 {total} 条",
        },
        home: {
            noPracticeWordsLeft: "没有可练习的单词了",
            noPracticeWordsDescription: "这篇文章里的词都已经比较熟悉了，这里暂时没有需要继续练习的内容。",
        },
        reading: {
            author: "作者",
            startPractice: "开始练习",
            preparingPractice: "正在准备练习",
            savePassage: "收藏这篇文章",
            removeSavedPassage: "取消收藏",
            previewSaveUnavailable: "预览文章暂不支持收藏",
            loginToSavePassages: "登录后可收藏文章",
            lookup: "释义",
            canonical: "词元",
            addToWordList: "加入词库",
            addedToWordList: "已加入词库",
            loginToAddWords: "登录后可加入词库",
            loadingDefinition: "正在加载释义...",
            noDefinition: "暂时还没有释义。",
            loginToViewDefinitions: "登录后可查看释义。",
            failedToLoadDefinition: "释义加载失败。",
        },
        about: {
            title: "关于 How To Say",
            intro: "How To Say 专注于沉浸式词汇学习。它把阅读、猜词、收藏和重复暴露串成一个连续流程，让新词始终和真实语境绑定，而不是停留在孤立的词表里。",
            readTitle: "在语境中阅读",
            readDescription: "通过文学片段、例句和句子级输入来学习，而不是只靠抽认卡。",
            practiceTitle: "主动练习",
            practiceDescription: "用猜词流程、分级练习和图片提示，把认识推进到真正能回忆出来。",
            bankTitle: "建立自己的词库",
            bankDescription: "边读边收词，之后随时回看，让练习始终聚焦在你还不熟悉的部分。",
            feedbackTitle: "发送反馈",
            feedbackDescription: "欢迎提交 bug、产品建议、缺失功能，或任何让你感到不清晰的地方。",
            feedbackPlaceholder: "告诉我们，什么能让 How To Say 更好用...",
            feedbackThanks: "感谢反馈，已经发送成功。",
            feedbackError: "提交失败，请稍后再试。",
            feedbackSending: "发送中...",
            feedbackSubmit: "提交反馈",
        },
        pricing: {
            eyebrow: "方案",
            title: "解锁完整学习工作流。",
            intro: "你可以先免费体验，再根据需要升级，获得更完整的高级练习、更深的词汇覆盖和个人学习管理能力。",
            unlockTitle: "Pro 能解锁什么",
            unlockDescription: "HowToSay Pro 面向希望获得更强结构感、更深输入和更好长期记忆控制的学习者。",
            advancedTitle: "更高级的练习模式",
            advancedDescription: "不再停留在基础猜词，加入更丰富的题型、音频辅助和更高强度的识别到回忆训练。",
            coverageTitle: "更深的内容覆盖",
            coverageDescription: "获得更广的词汇、更多例句和更强的上下文支持，让单词学习更贴近真实用法。",
            controlTitle: "更完整的个人学习控制",
            controlDescription: "维护自己的单词本，组织真正重要的内容，并用连续工作流持续复习。",
            requestProTitle: "申请 Pro",
            requestProContent: "请发送邮件到 bytegush@hotmail.com，说明你的学习场景和预期使用方式。",
            requestProConfirm: "返回",
        },
        pricingTiers: {
            free: {
                title: "免费版",
                price: "免费",
                description: "适合体验产品和轻量日常练习。",
                features: ["每日使用限制", "核心学习模式", "可申请 Pro 访问"],
                buttonText: "申请 Pro",
            },
            pro: {
                title: "Pro",
                price: "$4/年",
                description: "适合想完整使用产品的长期学习者。",
                features: [
                    "解锁全部学习模式",
                    "高级词汇与音频支持",
                    "更丰富的句子与例句覆盖",
                    "完整的词书管理能力",
                ],
                buttonText: "购买许可",
            },
            edu: {
                title: "教育版 Pro",
                price: "$2/年",
                description: "适合拥有教育邮箱认证的学生。",
                features: [
                    "解锁全部学习模式",
                    "高级词汇与音频支持",
                    "更丰富的句子与例句覆盖",
                    "完整的词书管理能力",
                ],
                buttonText: "购买许可",
            },
        },
        daily: {
            title: "每日猜词",
            intro: "一个简短的每日猜词挑战，结合文本线索和拼写练习。",
            loading: "正在加载今日挑战...",
            error: "暂时无法加载今天的单词。",
            empty: "今天的每日挑战还没有准备好。",
        },
        assessment: {
            eyebrow: "词汇等级测试",
            title: "估算你的实用词汇等级",
            intro: "这个小测试可以帮助你选择更合适的起始练习等级。它不是正式考试，但足以在开始前帮你校准词汇强度。",
            questions: "题目数",
            quickChecks: "个快速判断",
            currentLevel: "当前等级",
            signInToSave: "登录后可保存",
            question: "题目",
            answered: "你答对了 {score} / {total} 题。",
            answerAll: "答完所有题目后即可查看建议等级。",
            seeResult: "查看结果",
            recommendedLevel: "推荐等级",
            recommendedDescription: "可以先把它当成默认练习档位。如果觉得太简单或太密集，之后仍然可以在用户菜单里微调。",
            applying: "应用中...",
            applyLevel: "应用这个等级",
            signInToApply: "登录后应用",
            goToDaily: "去每日猜词",
            saveSuccess: "你的等级已更新为 {level}。",
            saveError: "更新等级失败，请稍后再试。",
        },
    },
}

export function formatCopy(template: string, values: Record<string, string | number>) {
    return template.replace(/\{(\w+)\}/g, (_, key: string) => String(values[key] ?? ""))
}
