import type { LiteraryPassageDetail, LiteraryTimelineItem, LiteraryTimelinePage } from "@/app/lib/literature-models"

const mockPassages: LiteraryPassageDetail[] = [
    {
        id: 1,
        slug: "analects-learning",
        title: "学而时习之",
        excerpt: "子曰：学而时习之，不亦说乎？有朋自远方来，不亦乐乎？人不知而不愠，不亦君子乎？",
        author_name: "孔子",
        work_title: "论语",
        work_year: -475,
        language: "zh",
        theme_accent: "#d6b06a",
        cover_image_url: null,
        is_active: true,
        is_featured: false,
        featured_at: null,
        display_order: 1,
        metadata: null,
        is_favorited: false,
    },
    {
        id: 2,
        slug: "mencius-people",
        title: "民为贵",
        excerpt: "民为贵，社稷次之，君为轻。是故得乎丘民而为天子，得乎天子为诸侯，得乎诸侯为大夫。",
        author_name: "孟子",
        work_title: "孟子",
        work_year: -320,
        language: "zh",
        theme_accent: "#c98f5b",
        cover_image_url: null,
        is_active: true,
        is_featured: false,
        featured_at: null,
        display_order: 2,
        metadata: null,
        is_favorited: false,
    },
    {
        id: 3,
        slug: "li-bai-wine",
        title: "将进酒",
        excerpt: "君不见黄河之水天上来，奔流到海不复回。君不见高堂明镜悲白发，朝如青丝暮成雪。人生得意须尽欢，莫使金樽空对月。",
        author_name: "李白",
        work_title: "将进酒",
        work_year: 752,
        language: "zh",
        theme_accent: "#7c8f6a",
        cover_image_url: null,
        is_active: true,
        is_featured: false,
        featured_at: null,
        display_order: 3,
        metadata: null,
        is_favorited: false,
    },
    {
        id: 4,
        slug: "su-shi-red-cliff",
        title: "赤壁赋",
        excerpt: "惟江上之清风，与山间之明月，耳得之而为声，目遇之而成色。取之无禁，用之不竭，是造物者之无尽藏也，而吾与子之所共适。",
        author_name: "苏轼",
        work_title: "赤壁赋",
        work_year: 1082,
        language: "zh",
        theme_accent: "#6d8ca8",
        cover_image_url: null,
        is_active: true,
        is_featured: true,
        featured_at: null,
        display_order: 4,
        metadata: null,
        is_favorited: false,
    },
    {
        id: 5,
        slug: "shakespeare-hamlet",
        title: "To be, or not to be",
        excerpt: "To be, or not to be, that is the question: Whether 'tis nobler in the mind to suffer the slings and arrows of outrageous fortune, or to take arms against a sea of troubles.",
        author_name: "William Shakespeare",
        work_title: "Hamlet",
        work_year: 1603,
        language: "en",
        theme_accent: "#9a6a7b",
        cover_image_url: null,
        is_active: true,
        is_featured: false,
        featured_at: null,
        display_order: 5,
        metadata: null,
        is_favorited: false,
    },
    {
        id: 6,
        slug: "austen-pride",
        title: "A truth universally acknowledged",
        excerpt: "It is a truth universally acknowledged, that a single man in possession of a good fortune, must be in want of a wife.",
        author_name: "Jane Austen",
        work_title: "Pride and Prejudice",
        work_year: 1813,
        language: "en",
        theme_accent: "#b88c6d",
        cover_image_url: null,
        is_active: true,
        is_featured: false,
        featured_at: null,
        display_order: 6,
        metadata: null,
        is_favorited: false,
    },
    {
        id: 7,
        slug: "bronte-jane-eyre",
        title: "I am no bird",
        excerpt: "I am no bird; and no net ensnares me: I am a free human being with an independent will.",
        author_name: "Charlotte Bronte",
        work_title: "Jane Eyre",
        work_year: 1847,
        language: "en",
        theme_accent: "#a67f5b",
        cover_image_url: null,
        is_active: true,
        is_featured: false,
        featured_at: null,
        display_order: 7,
        metadata: null,
        is_favorited: false,
    },
    {
        id: 8,
        slug: "woolf-room",
        title: "A room of one's own",
        excerpt: "A woman must have money and a room of her own if she is to write fiction.",
        author_name: "Virginia Woolf",
        work_title: "A Room of One's Own",
        work_year: 1929,
        language: "en",
        theme_accent: "#6d7ea5",
        cover_image_url: null,
        is_active: true,
        is_featured: false,
        featured_at: null,
        display_order: 8,
        metadata: null,
        is_favorited: false,
    },
    {
        id: 9,
        slug: "qu-yuan-li-sao",
        title: "路漫漫其修远兮",
        excerpt: "路漫漫其修远兮，吾将上下而求索。",
        author_name: "屈原",
        work_title: "离骚",
        work_year: -278,
        language: "zh",
        theme_accent: "#8d6e63",
        cover_image_url: null,
        is_active: true,
        is_featured: false,
        featured_at: null,
        display_order: 9,
        metadata: null,
        is_favorited: false,
    },
    {
        id: 10,
        slug: "tao-yuanming-drinking",
        title: "采菊东篱下",
        excerpt: "采菊东篱下，悠然见南山。",
        author_name: "陶渊明",
        work_title: "饮酒",
        work_year: 405,
        language: "zh",
        theme_accent: "#7b8d5a",
        cover_image_url: null,
        is_active: true,
        is_featured: false,
        featured_at: null,
        display_order: 10,
        metadata: null,
        is_favorited: false,
    },
    {
        id: 11,
        slug: "wang-wei-deer-enclosure",
        title: "空山不见人",
        excerpt: "空山不见人，但闻人语响。返景入深林，复照青苔上。",
        author_name: "王维",
        work_title: "鹿柴",
        work_year: 730,
        language: "zh",
        theme_accent: "#5f7f67",
        cover_image_url: null,
        is_active: true,
        is_featured: false,
        featured_at: null,
        display_order: 11,
        metadata: null,
        is_favorited: false,
    },
    {
        id: 12,
        slug: "du-fu-spring-view",
        title: "国破山河在",
        excerpt: "国破山河在，城春草木深。感时花溅泪，恨别鸟惊心。",
        author_name: "杜甫",
        work_title: "春望",
        work_year: 757,
        language: "zh",
        theme_accent: "#607d8b",
        cover_image_url: null,
        is_active: true,
        is_featured: false,
        featured_at: null,
        display_order: 12,
        metadata: null,
        is_favorited: false,
    },
    {
        id: 13,
        slug: "li-qingzhao-slow-slow",
        title: "寻寻觅觅",
        excerpt: "寻寻觅觅，冷冷清清，凄凄惨惨戚戚。",
        author_name: "李清照",
        work_title: "声声慢",
        work_year: 1130,
        language: "zh",
        theme_accent: "#ad7b8f",
        cover_image_url: null,
        is_active: true,
        is_featured: false,
        featured_at: null,
        display_order: 13,
        metadata: null,
        is_favorited: false,
    },
    {
        id: 14,
        slug: "xin-qiji-lantern",
        title: "蓦然回首",
        excerpt: "众里寻他千百度。蓦然回首，那人却在，灯火阑珊处。",
        author_name: "辛弃疾",
        work_title: "青玉案·元夕",
        work_year: 1181,
        language: "zh",
        theme_accent: "#8d6f8f",
        cover_image_url: null,
        is_active: true,
        is_featured: false,
        featured_at: null,
        display_order: 14,
        metadata: null,
        is_favorited: false,
    },
    {
        id: 15,
        slug: "cao-xueqin-red-chamber",
        title: "满纸荒唐言",
        excerpt: "满纸荒唐言，一把辛酸泪。都云作者痴，谁解其中味。",
        author_name: "曹雪芹",
        work_title: "红楼梦",
        work_year: 1791,
        language: "zh",
        theme_accent: "#a05a5a",
        cover_image_url: null,
        is_active: true,
        is_featured: false,
        featured_at: null,
        display_order: 15,
        metadata: null,
        is_favorited: false,
    },
    {
        id: 16,
        slug: "goethe-faust",
        title: "Two souls dwell in my breast",
        excerpt: "Two souls, alas, are dwelling in my breast, and one is striving to forsake its brother.",
        author_name: "Johann Wolfgang von Goethe",
        work_title: "Faust",
        work_year: 1808,
        language: "en",
        theme_accent: "#8a7b63",
        cover_image_url: null,
        is_active: true,
        is_featured: false,
        featured_at: null,
        display_order: 16,
        metadata: null,
        is_favorited: false,
    },
    {
        id: 17,
        slug: "pushkin-onegin",
        title: "My uncle has most honest principles",
        excerpt: "My uncle has most honest principles: when taken ill in earnest, he has by force won universal respect.",
        author_name: "Alexander Pushkin",
        work_title: "Eugene Onegin",
        work_year: 1833,
        language: "en",
        theme_accent: "#6f7fa3",
        cover_image_url: null,
        is_active: true,
        is_featured: false,
        featured_at: null,
        display_order: 17,
        metadata: null,
        is_favorited: false,
    },
    {
        id: 18,
        slug: "dickens-two-cities",
        title: "It was the best of times",
        excerpt: "It was the best of times, it was the worst of times, it was the age of wisdom, it was the age of foolishness.",
        author_name: "Charles Dickens",
        work_title: "A Tale of Two Cities",
        work_year: 1859,
        language: "en",
        theme_accent: "#8c6f56",
        cover_image_url: null,
        is_active: true,
        is_featured: false,
        featured_at: null,
        display_order: 18,
        metadata: null,
        is_favorited: false,
    },
    {
        id: 19,
        slug: "tolstoy-anna-karenina",
        title: "Happy families are all alike",
        excerpt: "Happy families are all alike; every unhappy family is unhappy in its own way.",
        author_name: "Leo Tolstoy",
        work_title: "Anna Karenina",
        work_year: 1878,
        language: "en",
        theme_accent: "#7e6651",
        cover_image_url: null,
        is_active: true,
        is_featured: false,
        featured_at: null,
        display_order: 19,
        metadata: null,
        is_favorited: false,
    },
    {
        id: 20,
        slug: "tagore-gitanjali",
        title: "Where the mind is without fear",
        excerpt: "Where the mind is without fear and the head is held high; where knowledge is free.",
        author_name: "Rabindranath Tagore",
        work_title: "Gitanjali",
        work_year: 1910,
        language: "en",
        theme_accent: "#8e8b55",
        cover_image_url: null,
        is_active: true,
        is_featured: false,
        featured_at: null,
        display_order: 20,
        metadata: null,
        is_favorited: false,
    },
    {
        id: 21,
        slug: "lu-xun-hometown",
        title: "希望本无所谓有",
        excerpt: "希望本无所谓有，无所谓无。这正如地上的路；其实地上本没有路，走的人多了，也便成了路。",
        author_name: "鲁迅",
        work_title: "故乡",
        work_year: 1921,
        language: "zh",
        theme_accent: "#5f7f88",
        cover_image_url: null,
        is_active: true,
        is_featured: false,
        featured_at: null,
        display_order: 21,
        metadata: null,
        is_favorited: false,
    },
    {
        id: 22,
        slug: "fitzgerald-gatsby",
        title: "So we beat on",
        excerpt: "So we beat on, boats against the current, borne back ceaselessly into the past.",
        author_name: "F. Scott Fitzgerald",
        work_title: "The Great Gatsby",
        work_year: 1925,
        language: "en",
        theme_accent: "#6c7f97",
        cover_image_url: null,
        is_active: true,
        is_featured: false,
        featured_at: null,
        display_order: 22,
        metadata: null,
        is_favorited: false,
    },
    {
        id: 23,
        slug: "borges-library",
        title: "The universe may be called a library",
        excerpt: "The universe, which others call the Library, is composed of an indefinite and perhaps infinite number of hexagonal galleries.",
        author_name: "Jorge Luis Borges",
        work_title: "The Library of Babel",
        work_year: 1941,
        language: "en",
        theme_accent: "#7a6d9c",
        cover_image_url: null,
        is_active: true,
        is_featured: false,
        featured_at: null,
        display_order: 23,
        metadata: null,
        is_favorited: false,
    },
    {
        id: 24,
        slug: "hemingway-old-man",
        title: "A man can be destroyed but not defeated",
        excerpt: "But man is not made for defeat. A man can be destroyed but not defeated.",
        author_name: "Ernest Hemingway",
        work_title: "The Old Man and the Sea",
        work_year: 1952,
        language: "en",
        theme_accent: "#5c7a8a",
        cover_image_url: null,
        is_active: true,
        is_featured: false,
        featured_at: null,
        display_order: 24,
        metadata: null,
        is_favorited: false,
    },
    {
        id: 25,
        slug: "victor-hugo-miserables",
        title: "Even the darkest night will end",
        excerpt: "Even the darkest night will end and the sun will rise.",
        author_name: "Victor Hugo",
        work_title: "Les Miserables",
        work_year: 1862,
        language: "en",
        theme_accent: "#8f7cba",
        cover_image_url: null,
        is_active: true,
        is_featured: false,
        featured_at: null,
        display_order: 25,
        metadata: null,
        is_favorited: false,
    },
    {
        id: 26,
        slug: "dante-divine-comedy",
        title: "In the middle of the journey of our life",
        excerpt: "In the middle of the journey of our life I found myself within a dark wood where the straight way was lost.",
        author_name: "Dante Alighieri",
        work_title: "The Divine Comedy",
        work_year: 1320,
        language: "en",
        theme_accent: "#86a06b",
        cover_image_url: null,
        is_active: true,
        is_featured: false,
        featured_at: null,
        display_order: 26,
        metadata: null,
        is_favorited: false,
    },
    {
        id: 27,
        slug: "cervantes-don-quixote",
        title: "Too much sanity may be madness",
        excerpt: "Too much sanity may be madness and the maddest of all, to see life as it is and not as it should be.",
        author_name: "Miguel de Cervantes",
        work_title: "Don Quixote",
        work_year: 1605,
        language: "en",
        theme_accent: "#b78f5e",
        cover_image_url: null,
        is_active: true,
        is_featured: false,
        featured_at: null,
        display_order: 27,
        metadata: null,
        is_favorited: false,
    },
    {
        id: 28,
        slug: "soseki-kokoro",
        title: "Loneliness is the price of freedom",
        excerpt: "Loneliness is the price of freedom.",
        author_name: "Natsume Soseki",
        work_title: "Kokoro",
        work_year: 1914,
        language: "en",
        theme_accent: "#b77474",
        cover_image_url: null,
        is_active: true,
        is_featured: false,
        featured_at: null,
        display_order: 28,
        metadata: null,
        is_favorited: false,
    },
    {
        id: 29,
        slug: "achebe-things-fall-apart",
        title: "The world has no end",
        excerpt: "The world has no end, and what is good among one people is an abomination with others.",
        author_name: "Chinua Achebe",
        work_title: "Things Fall Apart",
        work_year: 1958,
        language: "en",
        theme_accent: "#6ca288",
        cover_image_url: null,
        is_active: true,
        is_featured: false,
        featured_at: null,
        display_order: 29,
        metadata: null,
        is_favorited: false,
    },
    {
        id: 30,
        slug: "mahfouz-palace-walk",
        title: "Homes are beautiful in proportion",
        excerpt: "Homes are beautiful in proportion to our longing to be there.",
        author_name: "Naguib Mahfouz",
        work_title: "Palace Walk",
        work_year: 1956,
        language: "en",
        theme_accent: "#b0a061",
        cover_image_url: null,
        is_active: true,
        is_featured: false,
        featured_at: null,
        display_order: 30,
        metadata: null,
        is_favorited: false,
    },
    {
        id: 31,
        slug: "machado-posthumous-memoirs",
        title: "I am not exactly a writer who is dead",
        excerpt: "I am not exactly a writer who is dead, but a dead man who decided to write.",
        author_name: "Machado de Assis",
        work_title: "The Posthumous Memoirs of Bras Cubas",
        work_year: 1881,
        language: "en",
        theme_accent: "#6fa27e",
        cover_image_url: null,
        is_active: true,
        is_featured: false,
        featured_at: null,
        display_order: 31,
        metadata: null,
        is_favorited: false,
    },
    {
        id: 32,
        slug: "octavio-paz-sun-stone",
        title: "I search without finding",
        excerpt: "I search without finding, I write alone, there is no one, and yet there is someone.",
        author_name: "Octavio Paz",
        work_title: "Sun Stone",
        work_year: 1957,
        language: "en",
        theme_accent: "#88a46c",
        cover_image_url: null,
        is_active: true,
        is_featured: false,
        featured_at: null,
        display_order: 32,
        metadata: null,
        is_favorited: false,
    },
]

function toTimelineItem(passage: LiteraryPassageDetail): LiteraryTimelineItem {
    return {
        id: passage.id,
        slug: passage.slug,
        title: passage.title,
        preview: passage.excerpt.length > 90 ? `${passage.excerpt.slice(0, 90)}...` : passage.excerpt,
        author_name: passage.author_name,
        work_title: passage.work_title,
        work_year: passage.work_year,
        language: passage.language,
        theme_accent: passage.theme_accent,
        cover_image_url: passage.cover_image_url,
    }
}

export function getMockLiteratureTimeline(params: {
    page?: number
    perPage?: number
    authorName?: string
    workTitle?: string
} = {}): LiteraryTimelinePage {
    const page = params.page ?? 1
    const perPage = params.perPage ?? 12

    const filtered = mockPassages.filter((item) => {
        if (params.authorName && item.author_name !== params.authorName) {
            return false
        }

        if (params.workTitle && item.work_title !== params.workTitle) {
            return false
        }

        return true
    })

    const start = (page - 1) * perPage
    const data = filtered.slice(start, start + perPage).map(toTimelineItem)
    const lastPage = Math.max(1, Math.ceil(filtered.length / perPage))

    return {
        current_page: page,
        data,
        last_page: lastPage,
        next_page_url: page < lastPage ? `/hts/api/v1/literary-passages?page=${page + 1}` : null,
        per_page: perPage,
        total: filtered.length,
    }
}

export function getMockLiteraryPassageDetail(id: number | string): LiteraryPassageDetail | null {
    return mockPassages.find((item) => String(item.id) === String(id) || item.slug === id) ?? null
}
