ignoredBuiltDependencies:
  - unrs-resolver

overrides:
  glob@>=10.2.0 <10.5.0: '>=10.5.0'
  next@>=10.0.0 <15.5.10: '>=15.5.10'
  next@>=13.0.0 <15.0.8: '>=15.0.8'
  nodemailer@<7.0.7: '>=7.0.7'
  nodemailer@<=7.0.10: '>=7.0.11'
